### ISSUE TITLE
Brew install method requires Github credentials?

### ISSUE THREAD

**Issue by blopker** [jdxcode/rtx#1]
When I use the Homebrew install method on MacOS, it prompts me for my Github credentials. Is this expected?

```
❯ brew install jdxcode/tap/rtx
==> Tapping jdxcode/tap
Cloning into '/opt/homebrew/Library/Taps/jdxcode/homebrew-tap'...
Username for 'https://github.com':
```

**Comment by jdxcode** [comment]
I accidentally had the repo private, give it a try now and it should work.

**Comment by blopker** [comment]
Works! Thank you :)

Also, sidenote, excited for this. I never understood the asdf shim approach. I also like the improvements to runtime selection, like not having to know the exact version number to get the latest major release. Although, where does the name come from? I'd expect `rty` or similar for ease of typing like `asdf`. Maybe I'll just alias 😆

**Comment by jdxcode** [comment]
"runtime executer". idk I like putting "x" into things for some reason. I was mostly looking for something 3 characters that didn't seem to have many conflicts.

**Comment by jdxcode** [comment]
I haven't tested this, but I have written it such that it should work if the CLI is named something else. So feel free to put the binary as "rty" or even "asdf" if you really want to mess with your brain.

**Comment by blopker** [comment]
Fair enough. For what it's worth GeForce RTX is what I thought of first, but totally different market I guess. Thanks again!
