### ISSUE TITLE
`rtx activate --quiet` not showing warning messages

### ISSUE THREAD

**Issue by amoosbr** [jdxcode/rtx#109]
As a user, I miss the warning message with `--quiet`. My understanding of `--quiet` was to just disable the info messages like: `rtx: python@3.10.9`

Similar to the reported issue https://github.com/jdxcode/rtx/issues/104, I mainly set `rtx activate --quiet`, because I don't want to see a message with every new shell showing my global settings.
I'm fine with missing the `rtx: ...` or other info messages, but would like to see warnings.

Also fine, if I can no longer use `rtx activate --quiet`, but another option like via env variable to set messages to WARN or higher log levels.

With `rtx activate`:

```sh
❯ zi rtx
[WARN] [nodejs] version 18.13.0 not installed
rtx: python@3.10.9
❯ rtx where nodejs
/Users/user/.local/share/rtx/installs/nodejs/18.13.0
❯ node -v
v19.6.0
```

With `rtx activate --quiet`:
```sh
# no warning messages, about missing nodejs version, and not easy to detect due to node is still available. Just using the wrong version.
❯ zi rtx

❯ rtx where nodejs
/Users/user/.local/share/rtx/installs/nodejs/18.13.0
❯ node -v
v19.6.0
```

**Comment by jdxcode** [comment]
this was supposed to default to warn. Technically this means the "info" level would be hidden but I don't actually use that or think it's something I have any need for.

**Comment by amoosbr** [comment]
Thank you for the quick fix. Works as expected now.
