### ISSUE TITLE
Regex error parsing Ruby Gemfile

### ISSUE THREAD

**Issue by jordan-brough** [jdxcode/rtx#11]
Given a `~/.config/rtx/config.toml` like this:

```toml
legacy_version_file=true
```

And a Gemfile like this:
```ruby
# frozen_string_literal: true

ruby "3.0.5"

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
```
And _no_ `.tool-versions` or `.ruby-version` file.

When I `cd` into the directory with the `Gemfile`, or when I run `rtx ls` in that directory I get an error like this:
```
$ rtx ls

Error: 
   0: regex parse error:
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      1: ^\s*# frozen_string_literal: true
      2: 
      3: ruby "3.0.5"
      4: 
      5: source "https://rubygems.org"
      6: git_source(:github) { |repo| "https://github.com/#{repo}.git" }
                               ^
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      error: repetition quantifier expects a valid decimal

Location:
   src/plugins.rs:196
```

Which is from this line:
https://github.com/jdxcode/rtx/blob/bf15c1dcaaa3ddc5b4d8addd5d7ec4786ca60ccd/src/plugins.rs#L196

Perhaps something to do with asdf-ruby handling of `Gemfile` files?
https://github.com/asdf-vm/asdf-ruby/blob/13b395f9610b322a226abdc7167d56f9581a8fa4/bin/parse-legacy-file#L7

**Comment by jdxcode** [comment]
it's the caching, for some reason it isn't parsing it after it loads the first time. Fix should be in soon.

**Comment by jdxcode** [comment]
ah this was a really dumb bug, fix should be in soon

**Comment by jordan-brough** [comment]
Thanks!
