### ISSUE TITLE
Version resolution inconsistency

### ISSUE THREAD

**Issue by jatinn** [jdxcode/rtx#111]
Hi there, seeing some inconsistency on version resolution with the patch numbers.
Python seems to have patch version from `3.9.1 --> 3.9.16` and even though `3.9.1` is specified, it ends up resolving and bumping that up to the latest patch `3.9.16`.

```
cat sample/.tool-versions
python 3.9.1

cd sample
[WARN] [python] version 3.9.16 not installed

rtx install python@3.9.1
⢄ Installing runtime: python@3.9.16...^C
```

**Comment by jdxcode** [comment]
oof you're right this is a problem. Perhaps a short-term solution would be for me to not resolve if there is an exact matching version.

**Comment by jatinn** [comment]
awesome, thanks for the quick fix
