### ISSUE TITLE
Suggest using `~/.local/bin` in readme

### ISSUE THREAD

**Issue by ghostsquad** [jdxcode/rtx#115]
```
curl https://rtx.jdxcode.com/rtx-latest-macos-arm64 > ~/.local/bin/rtx
```

https://stackoverflow.com/questions/30274743/what-is-the-purpose-of-home-local

**Comment by jdxcode** [comment]
I much prefer `$HOME/bin` for binaries that I directly control like rtx. This is simply an example, and I see no benefit to advocating for this pattern personally.

**Comment by jdxcode** [comment]
I do appreciate bringing suggestions like this though! I certainly want rtx to be a good citizen where possible (which is why internally it does follow XDG spec)
