### ISSUE TITLE
add `RTX_FUZZY=1` env var config

### ISSUE THREAD

**Issue by eproxus** [jdxcode/rtx#117]
To follow the principle of least surprise, I think running `rtx global thing@latest` should save `thing latest` to the `.tool-versions` file and not `thing X.X.X` (where X.X.X happens to the the current latest version). 

This will allow users to continuously upgrade versions and always use the latest available automatically without having to run `rtx global ...` again and again.

EDIT by @jdxcode:
@eproxus wasn't aware of the `--fuzzy` flag which does precisely this, however this issue is still open because we can improve this behavior.

What we should actually do here is allow setting `--fuzzy` as the default behavior via `RTX_FUZZY=1` and similar config in settings. This means we'll also need to add either a `--no-fuzzy` (I think this is my preference) or `--pin` flag to local and global to reverse the behavior.

**Comment by jdxcode** [comment]
Use the `--fuzzy` flag for this behavior.

I think pinning should be the default behavior. If we used fuzzy matching, then it would break when a new version is released. Pinning is also a better default since it makes the behavior predictable.

This is also how asdf behaves and the reason they've been so against fuzzy matching. npm is another example that behaves like rtx.

**Comment by eproxus** [comment]
Ah, didn't know about the `--fuzzy` flag. Any change there could be a config for enabling `--fuzzy` by default on `global`?

**Comment by jdxcode** [comment]
If we can think of a semantic name for this I think it's a good idea. I'm not super happy with the name `--fuzzy` either but it was the best I could come up with

**Comment by eproxus** [comment]
If the flag will stay `--fuzzy` for now, I would suggest `global_fuzzy = false` in TOML.

**Comment by jdxcode** [comment]
I suspect we could do better but I haven't thought of anything yet. We will need to do this for local and have environment variable config as well

**Comment by jdxcode** [comment]
It's worth considering if we just had RTX_FUZZY=1 and fuzzy=true in the settings file configure local and global. Also if we did this we would probably then need a --pin flag to override fuzzy

**Comment by eproxus** [comment]
All good points. I think one of the strength of rtx, compared to asdf, is the fuzzy matching. Such a setting would upgrade the default experience when using rtx to be "smarter".

**Comment by jdxcode** [comment]
I thought about this more and decided your original thinking was actually the way this should behave. Now it will just save what you type in, so `rtx local python@3.11` will save a fuzzy match. This can be overridden with `rtx local --pin python@3.11`

**Comment by jdxcode** [comment]
at least for right now I don't think we need to put an env var in to make this configurable
