### ISSUE TITLE
Bug in semantic version sorting for fuzzy matches with i.e. `rtx exec`

### ISSUE THREAD

**Issue by amoosbr** [jdxcode/rtx#119]
This is probably an issue in the correct semantic version sorting combined with fuzzy version matching.

Expected:
`rtx exec python@3.10 -- python --version` --> `Python 3.10.10`

Actual:
`rtx exec python@3.10 -- python --version` --> `Python 3.10.9`

```sh
❯ rtx global --fuzzy python@3.10 python@3.11
python 3.10 3.11
❯ rtx ls
   python 2.7.18
   python 3.8.10
   python 3.9.12
   python 3.10.10
-> python 3.10.9             (set by ~/.tool-versions)
   python 3.11.1
-> python 3.11.2             (set by ~/.tool-versions)
❯ python --version
Python 3.10.9
❯ rtx exec python@3.10 -- python --version
Python 3.10.9
❯ rtx exec python@3.10.10 -- python --version
Python 3.10.10
```

**Comment by jdxcode** [comment]
`rtx global --fuzzy python@3.10 python@3.11`

wow. I don't think I intentionally thought of this use-case of setting the _same_ runtime with this command, glad to see that part worked at least.

**Comment by jdxcode** [comment]
fuzzy matching definitely isn't working correctly. These are different bugs but I think the solution is the same. I have a branch for consolidating and simplifying all of this logic—just haven't found the time to work on it. It's a pretty big change but it should make everything a lot simpler once I finish it.

**Comment by jdxcode** [comment]
looks like #121 fixes this:

```
~/src/rtx runtime-arg ❯ rtx x python@3.10 -- python -V
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
     Running `target/debug/rtx x 'python@3.10' -- python -V`
Python 3.10.10
~/src/rtx runtime-arg ❯ rtx ls
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/rtx ls`
-> golang 1.19.5             (set by ~/.tool-versions)
-> hadolint 2.10.0           (set by ~/.tool-versions)
-> java openjdk-19.0.2       (set by ~/.tool-versions)
-> jq 1.6                    (set by ~/src/rtx/.tool-versions)
-> nodejs 18.13.0            (set by ~/src/rtx/.node-version)
   python 3.10.10
   python 3.10.9
   python 3.11.1
-> python 3.11.2             (set by ~/.tool-versions)
-> ruby 3.2.0                (set by ~/.tool-versions)
-> rust 1.67.0               (set by ~/.tool-versions)
-> shellcheck 0.9.0          (set by ~/src/rtx/.tool-versions)
   shfmt 2.6.4
   shfmt 3.5.1
-> shfmt 3.6.0               (set by ~/src/rtx/.tool-versions)
```

**Comment by amoosbr** [comment]
@jdxcode I tested it this morning and it seems only partially fixed. I can confirm, that `rtx x python@3.10` is working, but the symlink is still pointing to `python 3.10.9` instead of `3.10.10`.

```sh
❯ rtx version
1.6.0 (built 2023-02-09)
❯ cat .tool-versions
python 3.10
❯ python --version
Python 3.10.9
❯ which python
/Users/user/.local/share/rtx/installs/python/3.10.9/bin/python
❯ rtx ls
   python 2.7.18
   python 3.8.10
   python 3.9.12
   python 3.10.10
-> python 3.10.9             (set by ~/.tool-versions)
   python 3.11.1
   python 3.11.2
-> ruby 3.1.3                (set by ~/.tool-versions)
```

I couldn't reopen the issue. Perhaps you can. Thanks.

**Comment by jdxcode** [comment]
this was an easy fix it turns out, I was just using the versioning library incorrectly

**Comment by jdxcode** [comment]
I don't know where we'd be without you @amoosbr, thanks for all this help

**Comment by amoosbr** [comment]
Working now. 👍
And thank you for developing `rtx` and providing such a great asdf replacement. It's working nicely for me and some of my colleagues.
