### ISSUE TITLE
Installing bun runtime fails with Read-only file system error

### ISSUE THREAD

**Issue by roele** [jdxcode/rtx#123]
While trying to install `bun` i get the following error.

```shell
❯ rtx install bun@latest
⡠ Installing runtime: bun@0.5.6...mktemp: mkdtemp failed on asdf-bun.sPd4: Read-only file system
Downloading Bun v0.5.6...
curl: (23) Failure writing output to destination
Fail: Couldn't download the Bun binary from https://github.com/oven-sh/bun/releases/download/bun-v0.5.6/bun-darwin-aarch64.zip
Fail: Failed to download Bun v0.5.6
⢄ Installing runtime: bun@0.5.6...[ERROR] [bun] script exited with non-zero status: exit code 1
[ERROR] Run with RTX_DEBUG=1 for more information.
```

Wondering where the `Read-only file system` comes from, respectively where it tries to create this temporary file. Installing other runtimes (e.g. maven) works fine.

---
macBook Pro M1, macOS 13.2, fish shell 3.6.0, rtx 1.5.3 (built 2023-02-07)

**Comment by jdxcode** [comment]
Works fine for me:
```
$ rtx x bun -- bun --version
0.5.6
```

This is something to do with tmp on your machine. I'd start here: https://github.com/cometkim/asdf-bun/blob/main/lib/utils.bash#L67

**Comment by roele** [comment]
Thanks for the hint @jdxcode. Definitively something fishy with the `mktemp` command on my machine.

**Comment by roele** [comment]
I figured that it depends on where i issue the command from. If i execute `rtx install bun@latest` in `/` i get the error as `mktemp` tries to create a dir in `/`.

**Comment by jdxcode** [comment]
This is more of a topic for the bun plugin, there isn't anything rtx could/should do here I don't think

**Comment by roele** [comment]
You're right, will file an issue for those guys to pick up.

**Comment by jdxcode** [comment]
I would suggest trying this in asdf just to verify this isn't an issue with rtx (I see no reason why it would be though)

**Comment by roele** [comment]
It's reproducible with `asdf` so this is clearly an issue with the bun plugin.
