### ISSUE TITLE
How do I keep stuff up to date?

### ISSUE THREAD

**Issue by alper** [jdxcode/rtx#144]
I checked docs and issues for this but can't find anything.

Say I installed nodejs@19 and now have:
`nodejs 19.6.0`

How do I keep this up to date and then do it for everything that I have installed?

So say nodejs 19.6.1 comes out, how do I automatically upgrade everything to it?

**Comment by jdxcode** [comment]
I think this is a duplicate of #49

**Comment by alper** [comment]
OK. Sure.
