### ISSUE TITLE
`-y` to accept prompts in non interactive sessions

### ISSUE THREAD

**Issue by Hypnotist1148** [jdxcode/rtx#188]
At the moment I do it like this

```bash
rtx install myplugin@latest
rtx global myplugin@latest
```

But it would be nice to base able to this

```bash
rtx global myplugin@latest -y
```

**Comment by jdxcode** [comment]
just set `RTX_MISSING_RUNTIME_BEHAVIOR=autoinstall`

**Comment by jdxcode** [comment]
I'd be open to making this a global flag. I don't like `-y` though. It's not clear _what_ you're saying yes to, right now we only prompt for this one thing but we may add other things later. I think granular prompts would be better.

`--missing-runtime-behavior=autoinstall` is certainly a mouthful, but that might be the best option unless we want to consider changing this to something more concise.

**Comment by Hypnotist1148** [comment]
True, something like `--install-missing`

**Comment by jdxcode** [comment]
it's actually an accident you were even able to pipe in "y". That was happening because I check if stderr is a tty, but not stdin. Note this prompt has also changed to multiselect so you should still be able to do that but you wouldn't need to pass "y" since everything defaults to enabled.
