### ISSUE TITLE
Can't install erlang

### ISSUE THREAD

**Issue by Blond11516** [jdxcode/rtx#196]
Environment: `Linux pop-os 6.1.11-76060111-generic #202302091138~1675975749~22.04~f771a7f SMP PREEMPT_DYNAMIC Thu F x86_64 x86_64 x86_64 GNU/Linux`
rtx version: `1.16.0 linux-x64 (built 2023-02-23)`

When trying to install erlang with rtx the installation always ends up failing with exit code 1.

Output from `RTX_DEBUG=1 RTX_VERBOSE=1 rtx install erlang 25.2.1`
```
[DEBUG] rtx::config: Config:
Files: ~/.tool-versions
Installed Plugins: awscli, elixir, erlang, gleam, golang, java, jq, mc, minio, nodejs, php, python, ruby, rust, shellcheck, shfmt, swiprolog, terraform, tiny, yarn
[DEBUG] rtx::cli: rtx install erlang 25.2.1
[DEBUG] rtx::toolset::builder: Toolset: erlang@25.2.1, nodejs@16.4.0, elixir@1.14.3-otp-25, gleam@0.26.2, yarn@1.22.11, ruby@3.0.3, python@3.10.4, java@adoptopenjdk-17.0.2+8, rust@1.65.0, php@8.1.8, terraform@1.2.7, swiprolog@7.6.4, minio@2022-10-08T20-11-00Z, mc@2022-10-09T21-10-59Z, golang@1.19, awscli@2.9.19
[DEBUG] rtx::runtimes: install erlang@25.2.1 25.2.1
rtx erlang@25.2.1 installing
[DEBUG] rtx::cmd: $ /home/blond/.local/share/rtx/plugins/erlang/bin/install 
rtx erlang@25.2.1   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
rtx erlang@25.2.1                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 98.8M  100 98.8M    0     0  13.4M      0  0:00:07  0:00:07 --:--:-- 15.3M
rtx erlang@25.2.1 APPLICATIONS INFORMATION (See: /home/blond/.local/share/rtx/plugins/erlang/kerl-home/builds/asdf_25.2.1/otp_build_25.2.1.log)
rtx erlang@25.2.1  * wx             : wxWidgets was not compiled with --enable-webview or wxWebView developer package is not installed, wxWebView will NOT be available
rtx erlang@25.2.1 error ✗
Error: 
   0: [erlang] script exited with non-zero status: exit code 1

Location:
   src/plugins/script_manager.rs:182

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

I've also found that building erlang works fine, it's only the last step of "installing" it to the rtx install folder that fails. Running `cp -r ~/.local/share/rtx/plugins/erlang/kerl-home/builds/asdf_25.2.1/otp_src_25.2.1 ~/.local/share/rtx/installs/erlang/25.2.1` finishes the installation and everything works fine.

I can successfully install erlang through asdf, or directly through kerl, so this leads me to believe that something about the way rtx runs installation scripts is messing with the erlang plugin's ability to run properly.

**Comment by Blond11516** [comment]
Testing on my Macbook, I get the same behavior with basically the same output from the installation command:
```
[DEBUG] rtx::config: Config:
  Files: ~/.tool-versions
  Installed Plugins: aws-sam-cli, awscli, awsebcli, dotnet, elixir, erlang, git, git-chglog, golang, golangci-lint, java, maven, nodejs, poetry, postgres, python, redis-cli, ruby, yarn
[DEBUG] rtx::cli: rtx install erlang 25.2.1
[DEBUG] rtx::cmd: $ /Users/etiennelevesque/.local/share/rtx/plugins/erlang/bin/list-all
[DEBUG] rtx::toolset::builder: Toolset: erlang@25.2.1, nodejs@16.18.0, elixir@1.14.3-otp-25, python@3.10.1, yarn@1.22.11, ruby@3.0.4, java@openjdk-11.0.2, awscli@2.6.2, git@2.39.1, aws-sam-cli@1.49.0, poetry@1.1.14, git-chglog@0.15.1, dotnet@6.0.302, maven@3.8.6, awsebcli@3.20.3, redis-cli@6.2.7, postgres@14.5, golang@1.18, golangci-lint@1.50.0
[DEBUG] rtx::runtimes: install erlang@25.2.1 25.2.1
rtx erlang@25.2.1 installing
[DEBUG] rtx::cmd: $ /Users/etiennelevesque/.local/share/rtx/plugins/erlang/bin/install
rtx erlang@25.2.1   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
rtx erlang@25.2.1                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 98.8M  100 98.8M    0     0  14.0M      0  0:00:07  0:00:07 --:--:-- 14.8M
rtx erlang@25.2.1 error ✗
Error:
   0: [erlang] script exited with non-zero status: exit code 1

Location:
   src/plugins/script_manager.rs:182

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

`uname -a`: `Darwin MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64`
`rtx --version`: `1.16.0 macos-x64 (built 2023-02-23)`

**Comment by Blond11516** [comment]
I've also noticed weird output with the spinner in the middle of the line when installing without debug logs and verbosity enabled. I have no idea if this has anything to do with the error, but I haven't noticed this with other plugins so I thought I'd mention it.

<img width="695" alt="Screenshot 2023-02-24 at 9 05 21 PM" src="https://user-images.githubusercontent.com/44734484/221330513-e8402acf-e8d8-4376-a26f-171f5ee13bb9.png">
<img width="578" alt="Screenshot 2023-02-24 at 9 05 29 PM" src="https://user-images.githubusercontent.com/44734484/221330516-b04e6142-5a1e-4ba0-b119-344e4a31b54e.png">

**Comment by jdxcode** [comment]
I'm able to repro. The plugin is piping stderr of the failing command to /dev/null: https://github.com/asdf-vm/asdf-erlang/blob/master/bin/install#L32

will update when I find out more...

**Comment by jdxcode** [comment]
got a real error message:

```
+ /Users/jdx/.local/share/rtx/plugins/erlang/kerl install asdf_25.2.1 /Users/jdx/.local/share/rtx/installs/erlang/25.2.1
ERROR: /Users/jdx/.local/share/rtx/installs/erlang/25.2.1 does not appear to be an empty directory.
```

I think the issue is that I create the following directories for the runtime:
* downloads/erlang/25.2.1
* installs/erlang/25.2.1
I'm pretty sure plugins generally expect the first one to be created, but apparently asdf doesn't create the second because erlang fails in that case.

I probably need to change this logic to not create the second but the problem is that I am already doing that for this marker that the runtime isn't completely installed, so I need to remove that.

**Comment by jdxcode** [comment]
btw the output is funky. If stdout isn't a tty for kerl it hides messages that should be shown on stderr—which doesn't make any sense. That's a red herring though, I can make it show all the same messages and it fails the same way.

**Comment by jdxcode** [comment]
I think I have a patch that will work, testing now

**Comment by jdxcode** [comment]
correction: asdf _does_ create that install directory. I added this thing that put a `.rtx-incomplete` file inside of that directory though and it's _that_ which apparently causes erlang to choke. It wants the directory completely empty.

**Comment by Blond11516** [comment]
Thanks a lot for the super quick fix!

**Comment by Blond11516** [comment]
And thanks for keeping the issue up to date regularly, it's really nice to have some visibility on how you found the issue and how you fixed it!

**Comment by jdxcode** [comment]
yeah and for context, that file is really useful since if you `ctrl-c` during an install or it otherwise fails in a invalid state (normally it tries to clear it out) it can know that the install wasn't successful and won't show it as an "installed" runtime

**Comment by Blond11516** [comment]
Yeah that makes sense, it's just unfortunate that kerl won't install in a non-empty directory.
I get that they don't want to accidentally overwrite something, just an unfortunate side effect.
