### ISSUE TITLE
[Feature request] `rtx shell <runtime>` similar to `pyenv shell`

### ISSUE THREAD

**Issue by Alex23rodriguez** [jdxcode/rtx#198]
Apart from `global` and `local`, there could be a `shell` command that switches to that runtime only for the current session. 
This may be accomplished via an environment variable (I don't know if there already is one) which takes grater precedence over local and global versions. 
This may be accompanied by a `rtx shell --unset <runtime>` to get rid of the env variable.

**Comment by Alex23rodriguez** [comment]
After reading up a bit, I realize this can sort of be accomplished with `rtx exec <runtime>@version -- <cmd>`. However, I still believe a solution with an env variable would be useful for longer sessions with a specific version.

**Comment by jdxcode** [comment]
this is actually really hard to do in rtx. It's not running inside of the shell like pyenv so I can't just set an env var. I would need to do something really messy like create a guid for the shell session and have a way to communicate with it to tell the activate script to set an env var.

However you can still get this behavior with 3 methods:

* `rtx nodejs@18 -- bash`
* `eval "$(rtx nodejs@18 env)"`
* `export RTX_NODEJS_VERSION=18`

I've talked about doing a command like `rtx shell` that would be the same as `rtx -- $SHELL`, but trying to determine the actual user's shell is surprisingly challenging to do reliably. I also don't feel like it's that much more to type.

You could probably write a bash function to make it easier for you to type as well. Maybe we could even include one in the activate script so it populates for people automatically.

**Comment by Alex23rodriguez** [comment]
I see. Thanks for clearing that up. In the hopes of getting a deeper understanding, could you briefly clarify / point me to the docs on what it means for rtx not to run on the shell? is it a deamon or something similar?

**Comment by jdxcode** [comment]
hmm I'm wrong actually, what I described is how nvm works. pyenv seems to work differently, `pyenv` is actually a shell function that gets created on init:

```
rtx on  activate ❯ pyenv init - bash
PATH="$(bash --norc -ec 'IFS=:; paths=($PATH);
for i in ${!paths[@]}; do
if [[ ${paths[i]} == "''/Users/jdxcode/.pyenv/shims''" ]]; then unset '\''paths[i]'\'';
fi; done;
echo "${paths[*]}"')"
export PATH="/Users/jdxcode/.pyenv/shims:${PATH}"
export PYENV_SHELL=bash
source '/opt/homebrew/Cellar/pyenv/2.3.13/libexec/../completions/pyenv.bash'
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(pyenv "sh-$command" "$@")"
    ;;
  *)
    command pyenv "$command" "$@"
    ;;
  esac
}
```

So it looks for `pyenv shell` and if it sees that it knows to re-exec it. Perhaps this could also work for us.

**Comment by jdxcode** [comment]
I also wonder why it does the same for rehash. I'll have to think about this a bit since it's not a simple solution and I'd have to re-implement this for all of the shells (it looks like fish is able to bypass this somehow). However it looks like it might be possible to do.

**Comment by Alex23rodriguez** [comment]
That sounds great! of course, it is completely up to you as to whether this is worth the effort or not, as I seem to be a bit out of my depth here :)
for now, i’ll resort to one of your previous suggestions, something like
` rtx_shell() { export RTX_$(echo $1 | tr '[:lower:]' '[:upper:]')_VERSION=$2 } `

**Comment by Alex23rodriguez** [comment]
(btw, am I missing something, or is this a bug?)
![IMG_1656](https://user-images.githubusercontent.com/22017085/221381160-086450bb-5808-48ae-bef8-faec12ba2240.jpeg)

**Comment by jdxcode** [comment]
is it activated? run `rtx doctor`

**Comment by Alex23rodriguez** [comment]
you’re awesome! thanks!
