### ISSUE TITLE
`rtx activate bash` and PATH inconsistencies

### ISSUE THREAD

**Issue by KaranAhlawat** [jdxcode/rtx#199]
I use bash as my login shell, and as such have placed `eval "$(rtx activate bash)"` in my `.bashrc`.
The unexpected thing is that doing so adds *each* runtime's binary path to the shell, as shown

```
/home/karan/.local/share/rtx/installs/nodejs/19.3.0/bin:/home/karan/.local/share/rtx/installs/poetry/1.3.1/bin:/home/karan/.local/share/rtx/installs/rust/stable/bin:/home/karan/.local/share/rtx/installs/leiningen/2.10.0/bin:/home/karan/.local/share/rtx/installs/php/8.2.3/bin:/home/karan/.local/share/rtx/installs/php/8.2.3/sbin:/home/karan/.local/share/rtx/installs/php/8.2.3/.composer/vendor/bin:/home/karan/.local/share/rtx/installs/tokei/12.1.2/bin:/home/karan/.local/share/rtx/installs/zoxide/0.9.0/bin:/home/karan/.local/share/rtx/installs/yarn/1.22.19/bin:/home/karan/.local/bin:/home/karan/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/var/lib/snapd/snap/bin:/home/karan/.yarn/bin:/home/karan/.yarn/bin
```

I don't believe this is the intended behavior? I can say that that specific line produces this output becomes removing it and logging back in again does not produce this PATH.

Not sure what's going on here, but any help is appreciated. Please do let me know if any other information is required.

Info:
rtx ver: 1.16.1
shell: bash 5.2.15
OS: linux-x64 (Fedora 37)

**Comment by jdxcode** [comment]
that's exactly what it's supposed to

**Comment by KaranAhlawat** [comment]
Then I'm even more confused, because it did not do this the first couple of times I sourced my `bashrc` with that `eval` in there.
And then for some reason, my shell can't pick up that `zoxide` (installed through rtx) is on the path.

Here's how I'm sequencing them
```
eval "$(rtx activate bash)"
eval "$(`rtx where zoxide`/bin/zoxide init bash)"
```

I use `rtx where zoxide` here, because if I don't then my shell complains that it can't find the `zoxide` executable. Which, by my understanding, should be on the path by then?

**Comment by jdxcode** [comment]
Is zoxide in your .tool-versions file?

**Comment by KaranAhlawat** [comment]
It is yes, in the global .tools-versions file.

**Comment by jdxcode** [comment]
What happens if you run `rtx install -f zoxide`? I get an error personally, and also in asdf:

```
~ ❯ asdf install zoxide latest
* Downloading zoxide release 0.9.0...
zoxide: Refusing to overwrite archive
tar: Error exit delayed from previous errors.
asdf-zoxide: Could not extract /Users/jdx/.asdf/installs/zoxide/0.9.0/bin/zoxide
asdf-zoxide: An error ocurred while installing zoxide 0.9.0.
```

**Comment by KaranAhlawat** [comment]
`rtx install -f zoxide` works fine for me.
![image](https://user-images.githubusercontent.com/56113511/221371624-c5796987-93eb-4ad1-84a2-23b689c75c17.png)

**Comment by jdxcode** [comment]
hm it seems to work on a linux machine, does this work:

```
rtx exec zoxide@latest -- zoxide -V
```

if so, then try this:

```
rtx exec -- zoxide -V
```

**Comment by KaranAhlawat** [comment]
The two commands work. I'm unsure how to monitor the output of `eval "$(rtx activate bash --status)"` though.

**Comment by jdxcode** [comment]
it will just show up in your terminal

**Comment by KaranAhlawat** [comment]
Well I don't see anything popping up 😅 . Again, I put the line in my .bashrc. Maybe a log out-log in will help?

**Comment by jdxcode** [comment]
nothing you do in your bashrc will take effect until you open a new shell session

**Comment by KaranAhlawat** [comment]
I really should learn how my shell works properly once and for all. As for the output, here it is.

```
rtx yarn@1.22.19 zoxide@0.9.0 tokei@12.1.2 php@8.2.3 leiningen@2.10.0 rust@stable poetry@1.3.1 nodejs@19.3.0
```

**Comment by jdxcode** [comment]
I see no reason why it shouldn't be working without the `rtx where`. I think you probably just didn't restart your shell session.

**Comment by KaranAhlawat** [comment]
Does restarting my computer count as a session restart?
I have also moved this eval into my `.bash_profile` now.

**Comment by jdxcode** [comment]
oh I see the problem, you're trying to execute zoxide right away. I think I know what is missing here. I'll work up a PR.

**Comment by KaranAhlawat** [comment]
Thank you for all the help! I have downloaded the RPM artifact from the GitHub actions as the latest release (1.17.0) just missed the PR by an hour or so.

**Comment by jc00ke** [comment]
Hi there, I think I'm experiencing this issue as well.

I have starship, zoxide and direnv all installed via rtx.

```
➜ rtx ls | rg "starship|zoxide|direnv"
direnv     2.32.2        ~/.tool-versions 2.32.2
starship   1.11.0        ~/.tool-versions 1.11.0
zoxide     0.9.1         ~/.tool-versions 0.9.1
```

I'll run through a few iterations of my `config.fish`:

```fish
rtx activate fish | source
source ~/.config/op/plugins.sh
starship init fish | source
zoxide init fish | source
# rtx exec -- zoxide init fish | source
eval (direnv hook fish)
# rtx exec -- direnv hook fish | source
```

will yield

```
Command 'zoxide' not found, but can be installed with:
sudo apt install zoxide
~/.config/fish/config.fish (line 109):
zoxide init fish | source
^
from sourcing file ~/.config/fish/config.fish
        called during startup
Command 'direnv' not found, but can be installed with:
sudo snap install direnv  # version v2.18.2, or
sudo apt  install direnv  # version 2.32.1-1ubuntu0.22.10.1
See 'snap info direnv' for additional versions.
~/.config/fish/config.fish (line 1):
direnv hook fish
^
in command substitution
        called on line 111 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
        called during startup
~/.config/fish/config.fish (line 111): Unknown command
eval (direnv hook fish)
     ^
from sourcing file ~/.config/fish/config.fish
        called during startup

➜ which zoxide
/home/jesse/.local/share/rtx/installs/zoxide/0.9.1/bin/zoxide

➜ z nvim
z: command not found
```

`z` is a fish `abbr` that is supposed to be set during `zoxide init fish | source`.

Now, if I change to use `rtx exec...`

```fish
rtx activate fish | source
source ~/.config/op/plugins.sh
starship init fish | source
# zoxide init fish | source
rtx exec -- zoxide init fish | source
# eval (direnv hook fish)
rtx exec -- direnv hook fish | source
```

then everything works as expected, as evidenced by:

```
~
➜ z nvim
~/.config/nvim via 🌙 v5.4.2
➜
```

So, for some reason, with zoxide and direnv and _NOT_ with starship, I need to use `rtx exec`. :confused: :man_shrugging: 

Hopefully this helps to either fix a hidden bug in `1.29.7 linux-x64 (a540ac6 2023-05-10)` or if it remains to be necessary, then future searchers can be helped.

**Comment by jdxcode** [comment]
this is expected behavior and documented in the readme: https://github.com/jdxcode/rtx#rtx-isnt-working-with-tmux

**Comment by jc00ke** [comment]
Thanks, though I totally missed that because it was in a `tmux` section, which I don't use. Would you be amenable to renaming that FAQ or breaking out a separate FAQ that explicitly addresses activation in an rc file?

**Comment by jdxcode** [comment]
yeah that's fine

**Comment by jdxcode** [comment]
Thinking about this a bit more, I’m not so sure actually. I mentioned this is another ticket but I think it is probably a bad practice to use `rtx activate` in a non-interactive situation.

Though I think one could make the argument that rc file and tmux *are* interactive even though they’re also scripts.

We can probably still document this more generally but I am wondering if there is a potential path that might be better here.

**Comment by jdxcode** [comment]
updated the README to be less tmux specific
