### ISSUE TITLE
Support for bin/latest-stable

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#21]
I didn't add this yet since I couldn't find a plugin that actually had one, but golang does so I can use that as a reference.

**Comment by jdxcode** [comment]
can you explain more? perhaps with pseudo commands? I'm not seeing how this would be used as you described.

**Comment by Hypnotist1148** [comment]
> can you explain more? perhaps with pseudo commands? I'm not seeing how this would be used as you described.

Sure, the output of `rtx latest {plugin}"` should output the latest runtime version of a plugin as i understand.

In the `latest-stable` script I'd get the latest git commit for the shorthand repo from master.
```bash
...
echo "$(git log HEAD..origin/master -n 1 --format="%H")"
```
