### ISSUE TITLE
Fish + Lua issue: `set: package.cpath : invalid variable name. See `help identifiers`

### ISSUE THREAD

**Issue by jesse-c** [jdxcode/rtx#210]
When a new shell window is open (in any of Kitty, Terminal.app, Tmux), this error is printed:

```
set: package.cpath : invalid variable name. See `help identifiers`

- (line 7):
set -e 'package.cpath '
^
from sourcing file -
        called on line 2 of file -
in function '__rtx_env_eval'
in event handler: handler for generic event 'fish_prompt'

(Type 'help set' for related documentation)
set: package.cpath : invalid variable name. See `help identifiers`

- (line 13):
set -gx 'package.cpath ' ' package.cpath .. '\'';/Users/jesse/.local/share/rtx/installs/lua/5.3.6/lib/lua/5.3/?.so;/Users/jesse/.local/share/rtx/installs/lua/5.3.6/luarocks/lib/lua/5.3/?.so'\'''
^
from sourcing file -
        called on line 2 of file -
in function '__rtx_env_eval'
in event handler: handler for generic event 'fish_prompt'

(Type 'help set' for related documentation)
```

In my `config.fish` I have `rtx activate fish | source`. When I run `lua -v` it does print out the expected version (`Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio`).

I've tried a few different versions of Lua and all have this issue for me.

`lua`: `5.3.6`
`uname -a`: `Darwin XXXX 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64`
`rtx --version`: `1.17.0 macos-arm64 (built 2023-02-25)`
`fish --version`: `fish, version 3.6.0`

**Comment by jdxcode** [comment]
yeah I can repro

**Comment by jdxcode** [comment]
it seems to work fine if you do `rtx x lua@latest -- lua -v`, which makes me think the issue is on outputting multiline env vars in fish, will update when I find out more

**Comment by jesse-c** [comment]
Thank you!

For me, I still have the same issue using `rtx x`. It may be specific of course to something else I have setup in Fish.

```shell
 N  ~ 15.1s ❱ rtx x lua@latest -- lua -v
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
set: package.cpath : invalid variable name. See `help identifiers`

- (line 9):
set -e 'package.cpath '
^
from sourcing file -
        called on line 2 of file -
in function '__rtx_env_eval'
in event handler: handler for generic event 'fish_prompt'

(Type 'help set' for related documentation)
set: package.cpath : invalid variable name. See `help identifiers`

- (line 18):
set -gx 'package.cpath ' ' package.cpath .. '\'';/Users/jesse/.local/share/rtx/installs/lua/5.4.4/lib/lua/5.4/?.so;/Users/jesse/.local/share/rtx/installs/lua/5.4.4/luarocks/lib/lua/5.4/?.so'\'''
^
from sourcing file -
        called on line 2 of file -
in function '__rtx_env_eval'
in event handler: handler for generic event 'fish_prompt'

(Type 'help set' for related documentation)
 I  ~ ❱
```

**Comment by jdxcode** [comment]
it worked, you can see the version being output at the top. You're just seeing the error from the activate script failing as well.

**Comment by jesse-c** [comment]
Ah yes, that makes sense!

**Comment by jesse-c** [comment]
Thank you! That fixed it for me. I installed from `HEAD` since I was impatient for the 1.18.0 release.
