### ISSUE TITLE
`rtx gc|prune|cleanup`

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#221]
we could have a command similar to `git gc` that would remove unreferenced versions of runtimes. To do this, we need to first have a list of all of the past referenced versions and/or .tool-versions files. We'll need to track this in the cache or something.

**Comment by jankatins** [comment]
This has another angle: if you create a python venv, per default it symlinks to the python it uses. Therefore, even if the python is not referenced in any .tool-versions file anymore, it could still be used in a venv. (thats actually the main reason I use rtx/asdf because brew was removing the old python version breaking my venvs.)

**Comment by jdxcode** [comment]
yes, and if people use `RTX_<PLUGIN>_VERSION` or `rtx x <PLUGIN>@<VERSION>` this wouldn't be aware and would remove those versions, unless we record those forever.

Right now I'm thinking that's just how it would work. If you use prune you'll potentially remove things you actually use.

Alternatively I could look at the atime of the runtimes and prune things older than 30 days or something.

**Comment by mark-thm** [comment]
How about landing a symlink back to any .tool-versions file that was ever used by rtx and gc can check whether the file still exists, and if it does, then use it to reference count appropriately.

**Comment by jdxcode** [comment]
That’s roughly what I was thinking but a symlink is a good idea to keep it simple

**Comment by sirikon** [comment]
Would be great if the command also displayed which version files were taken in consideration during the cleanup process

**Comment by jdxcode** [comment]
maybe a `rtx prune --dry-run` would help with that

**Comment by Wyatt-Stanke** [comment]
Shell script spaghetti in the meantime: 
`rtx ls | rg -v "⏵" | awk '{$1=$1;print}' | tr ' ' '@' | tr '\n' ' ' | xargs rtx rm`
Explanation:
```bash
rtx ls              | # Lists all installed tools
rg -v "⏵"           | # Filters tools by whether they are selected
awk '{$1=$1;print}' | # Removes leading whitespace
tr ' ' '@'          | # Converts ' ' into '@' (i.e. nodejs 19.7.0 -> nodejs@19.7.0)
tr '\n' ' '         | # Changes the newline-separated list of versions to a space-separated list
xargs rtx rm          # Removes all of the versions
```

**Comment by jdxcode** [comment]
This is out! Let me know how it works.
