### ISSUE TITLE
add ability to use file-based configuration for additional asdf plugin repos

### ISSUE THREAD

**Issue by mark-thm** [jdxcode/rtx#226]
I'd like to check in my .tool-versions file so that my CI environment and team can use tools all at the same version, but some asdf plugins are in repositories that aren't linked back to the main plugins list (e.g. https://github.com/looztra/asdf-promtool). I'd love to be able to throw the URL for the plugin into the .tool-versions file, perhaps something akin to:

```
promtool 2.24.0 https://github.com/looztra/asdf-promtool
```

Or some other file I could check in.

**Comment by jdxcode** [comment]
I'm considering this with the following syntax:

```
promtool@https://github.com/looztra/asdf-promtool 2.24.0
```

what you proposed is tricky since plugins can define multiple versions. I would need to do definitively if the string was a version or a repo.

This could also go into a lockfile (#141) or as part of a custom rtx config (which I want to create anyways), like `.rtx.toml`

**Comment by jdxcode** [comment]
in the meantime, you could setup a custom shorthand repo like this: https://github.com/jdxcode/rtx-shorthands

**Comment by mark-thm** [comment]
Ah, I wasn't intending to express a preference on syntax, the one you've defined seems adequate. I think if the shorthand repo doesn't match the specified one a warning should be enough.

`.rtx.toml` also seems very reasonable as a way to solve this, then as simple as dropping an extra mapping.

**Comment by jdxcode** [comment]
I've laid some groundwork for this in #241, currently it parses that config but it doesn't do anything with it just yet

**Comment by jdxcode** [comment]
I am considering doing this differently though and having a plugins section, e.g.:

```toml
[tools]
python = ['3.11', '3.10']
[plugins]
python = 'https://github.com/jdxcode/rtx-python'
```

I'm not sure which I like better just yet.

**Comment by jdxcode** [comment]
I am considering doing this differently though and having a plugins section, e.g.:

```toml
[tools]
python = ['3.11', '3.10']
[plugins]
python = 'https://github.com/jdxcode/rtx-python'
```

I'm not sure which I like better just yet.

**Comment by mark-thm** [comment]
Thanks!
