### ISSUE TITLE
rtx install swallows sudo password prompts

### ISSUE THREAD

**Issue by timriley** [jdxcode/rtx#228]
I just checked out rtx for the first time (thank you for making this tool! ❤️), and when I ran `rtx install` in my home directory for the given `.tool-versions`:

```
golang 1.18.4
java openjdk-19.0.1
nodejs 16.15.0
postgres 14.2
ruby 3.1.2
```

rtx wouldn't exit, because the install of `java openjdk-19.0.1` was waiting for a sudo password to be provided.

I wasn't aware of this initially, so after hitting `<return>` a number of times, I noticed some output indicating it might've been prompting for this password, as well as the little padlock symbol that macOS shows when a secure prompt is active at the bottom right of rtx's current output.

At that point, I just blindly entered my password, which seemed to actually work and allowed the installation of java to complete.

**To Reproduce**

On macOS (though the problem may be present in other operating systems), run `rtx install java openjdk-19.0.1`.

After a few minutes, once the installation is nearly complete, you'll see something like this:

<img width="762" alt="Screenshot 2023-02-28 at 11 20 07 am" src="https://user-images.githubusercontent.com/3134/221719666-b5705ed4-9cb3-4141-9a12-1109707018c3.png">

Note the little padlock on the bottom RHS of the output.

If you just hit `<return>` here, you'll see hint from the extra output text that this is actually a password prompt:

<img width="762" alt="Screenshot 2023-02-28 at 11 20 16 am" src="https://user-images.githubusercontent.com/3134/221719773-f0f6909b-64e2-4b2e-a7c6-69004c69920e.png">

And then if you finally enter your password and hit `<return>`, then the command will complete:

<img width="762" alt="Screenshot 2023-02-28 at 11 20 20 am" src="https://user-images.githubusercontent.com/3134/221719820-2c9bbb93-c411-4a06-b93f-2a41ee7d4ca5.png">

**Expected behavior**

Password prompts should be made clearer, so they're not missed by the user, and so the user can be confident that when they enter their password, it is going straight to the command prompting for it, and not into some other part of rtx.

**`rtx doctor` output**

```
Config:
  Files: ~/.tool-versions
  Installed Plugins: golang, java, nodejs, postgres, ruby
[ERROR] rtx is not activated, run `rtx help activate` for setup instructions
Error:
   0: 1 problems found

Location:
   src/cli/doctor.rs:51

Version:
   1.18.2 macos-arm64 (built 2023-02-27)

Suggestion: Run with RTX_DEBUG=1 for more information.

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

n.b. at the time of report, I have not activated rtx yet, but the issues here are related to `rtx install` only.

**Comment by jdxcode** [comment]
There's a few things going on here, but first: get rid of your asdfrc which has `java_macos_integration_enable = yes`. That setting should not be used with rtx.

**Comment by jdxcode** [comment]
this whole stdin thing is going to be a problem. Perhaps we could have a `rtx install --raw` mode that only installs runtimes one-by-one and accepts stdin—otherwise we should disable it.

**Comment by timriley** [comment]
Thanks for the tip regarding removing `java_macos_integration_enable = yes`, @jdxcode! That removed the prompt for the password in this specific case.

Glad to see you clarifying stdin handling in the meantime. Looking forward to giving rtx a good try from here!

**Comment by jdxcode** [comment]
definitely let me know if you see any more strange behavior
