### ISSUE TITLE
[bug] Plugin install fails when variable tested

### ISSUE THREAD

**Issue by chessmango** [jdxcode/rtx#246]
**Describe the bug**
When attempting to install a plugin using `rtx plugins install micro https://github.com/YR-ZR0/asdf-micro`, I get an error:
`/home/foobar/.local/share/rtx/plugins/micro/bin/list-all: line 5: OAUTH_TOKEN: unbound variable`

**To Reproduce**
`rtx plugins install micro https://github.com/YR-ZR0/asdf-micro`

**Expected behavior**
Plugin should install correctly

**`rtx doctor` output**

```
rtx version:
  1.20.1 linux-x64 (built 2023-03-02)

shell:
  /bin/zsh
  zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

rtx environment variables:
  RTX_SHELL=zsh

config:
  Files: ~/.tool-versions
  Installed Plugins: awscli, azure-cli, fzf, glab, golang, helm, hwatch, iamlive, jiq, jq, kubectl, micro, mkcert, nodejs, shellcheck, shfmt, terraform, terragrunt

settings:
  {"experimental": "false", "missing_runtime_behavior": "prompt", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

toolset:
  jq@1.6, shellcheck@0.9.0, shfmt@3.6.0, mkcert@1.4.4, terraform@1.3.9, nodejs@18.14.2, terragrunt@0.43.2, glab@1.25.3, kubectl@1.26.1, awscli@2.9.23, golang@1.20.1, helm@3.11.1, azure-cli@2.45.0, iamlive@0.51.2, hwatch@0.3.9, fzf@0.38.0, jiq@0.7.2

No problems found
```

**Additional context**
Specifically this appears to be because `$OAUTH_TOKEN` is tested as part of the `list-all` script, to avoid GitHub ratelimit issues. [The shell script itself](https://github.com/YR-ZR0/asdf-micro/blob/ac6e54359f578324daf5ec853c84de0ced439968/bin/list-all#L5-L7) checks out and works just fine - `-n` exits 0 if a string lenth is non-zero, and seems to work just fine from a given shell

**Comment by jdxcode** [comment]
this is an issue with the plugin which has `set -u` set, they should be doing `"${OAUTH_TOKEN:-}"` to default it

**Comment by chessmango** [comment]
> this is an issue with the plugin which has `set -u` set, they should be doing `"${OAUTH_TOKEN:-}"` to default it

Aah, gotcha - didn't think to check. Cool, ignore this then :D thanks!
