### ISSUE TITLE
Revert previously applied `rtx shell <runtime>`

### ISSUE THREAD

**Issue by gl3b4ik** [jdxcode/rtx#252]
Is there any way to revert previously applied `rtx shell <runtime>` command? `asdf shell` has option `--unset` for this behavior, maybe `rtx` can do the same?

**Comment by jdxcode** [comment]
I can add this, but you can also just do `unset RTX_NODEJS_VERSION`

**Comment by gl3b4ik** [comment]
Well, it seems like `unset` is not working propertly, [![asciicast](https://asciinema.org/a/7mHHFFpkvs5ij1pDKfIMXDDfA.svg)](https://asciinema.org/a/7mHHFFpkvs5ij1pDKfIMXDDfA)
