### ISSUE TITLE
rtx 1.21.5 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [jdxcode/rtx#260]
👋 looks like the 1.21.5 release was not completed, raise an issue in here for some awareness, https://github.com/jdxcode/rtx/actions/runs/4331559515/jobs/7563471994, thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/124802

**Comment by jdxcode** [comment]
Yeah that was weird, I thought I broke it so cut another release but it looks like it was GitHub's API that was failing. It worked on retry.
