### ISSUE TITLE
Add support for nushell

### ISSUE THREAD

**Issue by LisaScheers** [jdxcode/rtx#261]
add support for nushell https://www.nushell.sh/

**Comment by jdxcode** [comment]
We should do this, but I wanted to let you know that you can use any shell with rtx if you use the experimental shims functionality (which is about ready to come out of "experimental" I think)

**Comment by BeeeQueue** [comment]
I tried to set it up with the experimental shims and nushell, but all I get is `x is not a valid shim`, with nothing in the debug logs 😕

**Comment by jdxcode** [comment]
do the shims work in other shells?

**Comment by BeeeQueue** [comment]
Doesn't work in bash either, do the shims need some shell configuration to work?

**Comment by jdxcode** [comment]
hmm seems we need a better error message for installed but not active runtimes
