### ISSUE TITLE
Error installing `heroku-cli`

### ISSUE THREAD

**Issue by niccolomineo** [jdxcode/rtx#265]
I am trying to install the `heroku-cli`asdf package on a MacBook Air M1 with Mac Os 13.2.1, but I am getting:

```zsh
~ # rtx install heroku-cli
/Users/<username>/.local/share/rtx/plugins/heroku-cli/lib/utils.bash: line 56: echoerr: command not found
/Users/<username>/.local/share/rtx/plugins/heroku-cli/lib/utils.bash: line 56: echoerr: command not found
rtx heroku-cli@8.0.1 downloading                                           ✗ 0s rtx failed to install heroku-cli@8.0.1
rtx Run with RTX_DEBUG=1 for more information
```

**Comment by jdxcode** [comment]
1.22.0 has a fairly serious bug in it, runtime installs seem to fail about 30% of the time. I'm surprised the E2E tests passed. I know what happened though, just trying to find a good fix. 1.22.1 should be out within an hour. If you're having trouble, stay with 1.21 for now

Or just try installing again.

**Comment by jdxcode** [comment]
I'm just waiting to see if my fix works right now: https://github.com/jdxcode/rtx/actions/runs/4338307105/jobs/7574910517

If it doesn't, I'm just going to roll back the change that caused this.

**Comment by niccolomineo** [comment]
Thanks, I am going to wait for you to release the update.

**Comment by jdxcode** [comment]
1.22.1 is rolling out now, the problem was a race condition

**Comment by jdxcode** [comment]
#267 is the real fix

**Comment by niccolomineo** [comment]
I am still having the problem after the latest update.

```zsh
~ rtx self-update && rtx install heroku-cli                23:47:08
Checking target-arch... macos-arm64
Checking current version... v1.22.0
Checking latest released version... v1.22.4
New release found! v1.22.0 --> v1.22.4
New release is compatible

rtx release status:
  * Current exe: "/Users/<username>/.local/share/rtx/bin/rtx"
  * New exe release: "rtx-v1.22.4-macos-arm64"
  * New exe download url: "https://api.github.com/repos/jdxcode/rtx/releases/assets/98176001"

The new release will be downloaded/extracted and the existing binary will be replaced.
Do you want to continue? [Y/n] Y
Downloading...
[00:00:00] [========================================] 10.55 MiB/10.55 MiB (0s) DoneExtracting archive... Done
Replacing binary file... Done
Updated rtx to 1.22.4
/Users/<username>/.local/share/rtx/plugins/heroku-cli/lib/utils.bash: line 56: echoerr: command not found
/Users/<username>/.local/share/rtx/plugins/heroku-cli/lib/utils.bash: line 56: echoerr: command not found
rtx heroku-cli@8.0.1 downloading                                           ✗ 0s rtx failed to install heroku-cli@8.0.1
rtx Run with RTX_DEBUG=1 for more information
```

**Comment by niccolomineo** [comment]
Just tested it with v1.21.0 and I am getting an error as well.

**Comment by jdxcode** [comment]
this is an issue with the plugin, not rtx because I get the exact same error in asdf. I'll see if I can fix it upstream.

**Comment by jdxcode** [comment]
see https://github.com/treilly94/asdf-heroku-cli/pull/4

you can use my fork with `rtx plugin install -f heroku-cli https://github.com/jdxcode/rtx-heroku-cli`

I have also noticed that heroku published a v8.0.0 and v8.0.1 versions though they appeared to publish a couple of versions afterwards that are newer but on the v7. This doesn't appear to be intentional so v8 I think are just old versions.

**Comment by jdxcode** [comment]
```
rtx-heroku-cli  main [!?⇡] ❯ rtx x heroku-cli@7.67.2 -- heroku -v
✔ Select versions to install · heroku-cli@7.67.2
rtx heroku-cli@7.67.2 heroku-cli 7.67.2 installation was successful!                   ✓ 16sheroku/7.67.2 darwin-x64 node-v14.19.0
```

**Comment by niccolomineo** [comment]
Thanks for all your support! 

How am I supposed to launch the Heroku CLI once installed?

Simply doing `heroku` does not work.

I have this in my `.zshrc`:

```
eval "$(~/.local/share/rtx/bin/rtx activate zsh)"
```

Where are executables located?
