### ISSUE TITLE
output for (easier) programmatic consumption

### ISSUE THREAD

**Issue by z0w13** [jdxcode/rtx#283]
It would be nice to have cleaner output for consumption by shell scripts or other programs, main thing I'm running into is `rtx ls <plugin>` having quite a lot going on whereas `rtx ls-remote <plugin>` is way cleaner for programmatic consumption.

**Comment by jdxcode** [comment]
what is it you're trying to do exactly? `rtx current` might be a better fit

**Comment by jdxcode** [comment]
I don't love that we have 2 commands that are so similar... I really tried to avoid this situation but it's done in part to make rtx a bit more of a drop-in replacement for asdf

**Comment by z0w13** [comment]
I'm using it to remove all X.X.* versions apart from the latest, and also using it to reinstall versions that broke due to system library updates or packages that broke due to similar reasons.

Aka, iterating over all installed versions

**Comment by jdxcode** [comment]
Makes sense, I'd be open to a --raw flag or something. What do you think?

**Comment by z0w13** [comment]
basically giving it the same output formatting to ls-remote then I presume? That'd work

**Comment by jdxcode** [comment]
well it can't be that since that doesn't display the plugin, it would have to be more like `rtx current` but show installed versions, not current ones

**Comment by jdxcode** [comment]
oh do you mean `rtx ls <PLUGIN>`? yeah I guess that could just show the version if `--raw` is passed

**Comment by jdxcode** [comment]
oh do you mean `rtx ls <PLUGIN>`? yeah I guess that could just show the version if `--raw` is passed

**Comment by z0w13** [comment]
An alternative could be json output but that sounds like it'd be a bit more... involved. But yes specifically `rtx ls <PLUGIN>` is what I meant
