### ISSUE TITLE
env variables diff issue with shells other than bash

### ISSUE THREAD

**Issue by issmo** [jdxcode/rtx#288]
The env diff is broken with some plugins exporting environment variables with bash
some environment variables are rendered differently by bash and their bash version gets included by rtx as patched variables while they should not.

I have provided a pull request which runs the plugin bash scripts with a new minimal environment to avoid this behaviour.

**Comment by jdxcode** [comment]
can you give me more specifics on exactly what you're seeing? I'm not sure what we want is for this script to run in a completely empty environment.

**Comment by issmo** [comment]
I am having issue with some environment variables being modified as a result of the execution of plugins' bash scripts.
I am using fish shell on macOS with tide plugin as prompt. setting a java version in .tools-version triggers the execution of ~/.local/share/rtx/plugins/java/bin/exec-env which sets the JAVA_HOME environment variable.
rtx executes this script and reads back the environment variables from bash. Some of the environment variables are detected as modified while they are not (for ex, in my case, the _tide_location_color containing escape character and KITTY_PUBLIC_KEY). I have noticed that bash returns slightly different values (uppercase escape char) for these user env variables which sets back these bash modified values in fish and breaking some functionalities (prompt, etc..).
The rationale of the suggested change is to build a new environment with only the necessary ASDF environment variables needed.
And you are completely right, the need is not to have a completely blank slate for these scripts but rather and "ASDF" compatible environment without user defined env variables. I am still working on completing the pull request

**Comment by jdxcode** [comment]
Your solution is not going to work. Many plugins need access to variables that are not just ASDF_.

For one example, see asdf-golang which only sets GOPATH if not already set.

**Comment by jdxcode** [comment]
it sounds like what we need to do is fix the escaping/unescaping logic to be compatible with these cases so they don't appear as a change

**Comment by issmo** [comment]
This looks a safer way. I'll cancel the pull request which is way too specific to my use case.

**Comment by jdxcode** [comment]
I hate that a lot of that escaping/unescaping is manual, however I couldn't figure out a way to do it that's compatible with bashv3.

If you can find a way to do more of this in bash and less of it that's manually escaping everything I'm all ears.

**Comment by issmo** [comment]
Do you think it would be safer to have a dedicated rtx command/utility (for example: rtx env) that is responsible to output the environment variables instead of the command "export -p"? The variables would be collected through rust vars()
Would this be a viable option?

**Comment by jdxcode** [comment]
I'm conscious of performance since this script is sometimes on the critical path. Anything we do will increase the time it takes a shim to execute or `hook-env` to run if it's not cached (which it can't always be).

I'd rather something that isn't as safe even if it saves 1ms.

**Comment by gwww** [comment]
I've run into a similar problem. I started a discussion here: https://github.com/jdxcode/rtx/discussions/292 (to tie the threads together).

Is there anything I can provide to help move towards a resolution of this? I'm not a rust programmer so cannot provide code. Although I did take a peek at the code and the `shell-escape` code. It did not give me any clues.

The bit of my environment variables that breaks are here: https://github.com/gwww/dotfiles/blob/main/.config/zsh/rc.interactive#L45-L51

What appears to be happening is that when environment variables are reinstated there is an extra `\` at the beginning (possible more than just the beginning, but this serves as a good example). So for example a correctly defined environment variable looks like this: `export LESS_TERMCAP_ue=$'\E[0m'` and when it gets put back its: `export LESS_TERMCAP_ue=$'\\E[0m'`. The `\` to that indicates the next character is special has been changed to `\\` which is a literal backslash.

**Comment by gwww** [comment]
Reading the zsh manual further I found that section 5.1.3 is relevant: https://zsh.sourceforge.io/Guide/zshguide05.html. A string with escape characters in it should start with `$` which explains why when the variables are put back they do not work. I don't think I can change anything in how I define stuff in my zshrc to fix this.

**Comment by jdxcode** [comment]
I've had a very busy week so haven't had any time to diagnose this or look at rtx much at all. I may not have any time this weekend either. However I am almost certain the issue is because we're not using shell-escape or any other library for shell escaping and instead manually escaping bash's output—because I couldn't get shell-escape to work with newlines. The escaping happens in [here](https://github.com/jdxcode/rtx/blob/main/src/env_diff.rs#L108-L110). The issue may also be in the unescaping portion [here](https://github.com/jdxcode/rtx/blob/main/src/shell/bash.rs#L66-L68)—or I suspect it might be in both places.

**Comment by jdxcode** [comment]
even if you don't have much rust experience, if you managed to figure out a failing test case I can add to this section that would be very helpful: https://github.com/jdxcode/rtx/blob/main/src/env_diff.rs#L282-L295

**Comment by jdxcode** [comment]
it's worth noting that direnv gets around this problem in a totally different way by actually executing direnv inside of a similar hook: https://direnv.net/man/direnv-stdlib.1.html#codedirenvload-ltcommand-generating-dump-outputgtcode

that's similar to what @issmo suggested, however I have been hesitant for performance reasons as I mentioned in my previous comment. Rust is very fast, but I think it would still likely add 1-2ms at best and possibly a lot more.

**Comment by gwww** [comment]
Thanks! I hope you don't think I was rushing/pressuring you. My intention was just to give as much info as I could.

Looking at the test case you provided, I'm assuming it runs those test strings through the same `activate` sequence that we're seeing the problem with. So it round trips the environment variables by unsetting and then setting them back (incorrectly).

So, if I understand correctly then a Rust string to add to that test would be `"\x1B[0m"` (key name unimportant). What I think I'm seeing after the round trip is the Rust string `"\\x1B[0m"`; i.e.: the extra `\` causes the escape character to not be treated as such.

In zsh, and I believe also in bash, to write the Rust string `"\x1B[0m"` it is written as `$'\E[0m'` where $ says this string has sequences that are escaped with a `\`, `\E` is the equivalent of the Rust `\x1B`, and the `[0m` is the same literal string in both Rust and zsh.

That's my first cut. I'll poke away through the evening and see if there is more I can add here.
