### ISSUE TITLE
Nushell support

### ISSUE THREAD

**Issue by toadslop** [jdxcode/rtx#293]
Hi there. I tried out rtx and love it. I also tried out nushell and love it. But there’s a problem: no nushell support for rtx. I’m working on writing a nushell script to activate rtx but I’m not so good at bash scripting, so I’m not always sure if what I’m writing is faithfully reproducing what the scripts for zsh and bash and the others are doing. In the documentation you said you wouldn’t mind helping users set up new shells so I was wondering if you could help me out. If you’re ok to help out, just let me know here and I’ll post more about what I have already and what specific parts I need help with. Thanks!

**Comment by Solidsilver** [comment]
There's already an issue for this. See #261

**Comment by jdxcode** [comment]
just submit a draft PR with what you have and we can chat about it

**Comment by toadslop** [comment]
Thanks! A quick question before I do. I have a nushell hook that runs rtx's hook-env command when I change directories to update nushell's environment variables and it works. For example, if I .tool-versions with go 1.15 in it, and I print the environment variables, I get this:

```
GOPATH                     │ /Users/brianheise/.local/share/rtx/installs/go/1.15/packages           
GOROOT                    │ /Users/brianheise/.local/share/rtx/installs/go/1.15/go    
```

So far so good. But, when I run `go version` it still outputs `go version go1.20.2 darwin/amd64`.

To help me debug this issue, I was wondering if you knew whether there is some other process that rtx should be doing that I didn't handle, or do you think this is likely to be a nushell issue?

**Comment by jdxcode** [comment]
you need to run hook-env every time the prompt is displayed, not just when the directory is changed. Otherwise it won't work if you edit tool-versions and don't re-enter the directory.

It looks to me like it's not updating PATH: https://www.nushell.sh/book/configuration.html#path-configuration

**Comment by toadslop** [comment]
You're right -- rtx is updating variables like GOPATH and GOROOT but it isn't updating the PATH. Do you have any ideas about what might be causing that?

**Comment by jdxcode** [comment]
not without looking at your code

**Comment by bnheise** [comment]
Found the problem. Rtx outputs the path variable twice -- the old path and the new path. Normally this wouldn't be a problem, except in nushell we can't evaluate string output as code, so instead I was parsing the environment variables to a hashmap and then loading them into the environment. Because PATH was provided twice, the old path was always overwriting the new path. It works now.
