### ISSUE TITLE
Feature request: improved direnv-like features

### ISSUE THREAD

**Issue by ericbn** [jdxcode/rtx#310]
Hi 👋

First thank you for rtx and the great improvements over asdf that you've implemented!

I've just migrated almost all my projects from rtx to asdf, using .rtx.toml files. I had two .envrc files with direnv features not yet supported:
```
layout node
```
which basically does
```shell
export PATH="${PATH}:${PWD}/node_modules/.bin"
```
and also:
```
layout pipenv
```
which basically does
```shell
export VIRTUAL_ENV="$(pipenv --venv)"
export PATH="${PATH}:${VIRTUAL_ENV}/bin"
export PIPENV_ACTIVE=1
````

I'd like to be able to alter existing environment variables or set new ones using shell scripts. Having a "global" shell script with utility functions [like direnv has](https://github.com/direnv/direnv/blob/master/stdlib.sh) would be a great addition. And being able to use our preferred shell (e.g. zsh), instead of only bash, would be amazing too.

**Comment by jdxcode** [comment]
have a look at #313 which makes it easy to add node_modules/.bin to PATH:

```
[env]
PATH = ["./node_modules/.bin", "$PATH"]
```

I can have a look at putting the pipenv functionality into rtx-python, should be able the same as the current venv config.

BTW you can sort of do the shell exporting env vars today if you write your own plugin that has a bin/exec-env script inside of it. We could do something like direnv and allow putting config into a bash script but that would be noticeably slow and it might have to run _every_ prompt. I'd prefer sticking to declarative toml config since we don't need to launch a bash process like that.

**Comment by jdxcode** [comment]
also see https://github.com/jdxcode/rtx-python/pull/5 for pipenv support

**Comment by jdxcode** [comment]
I think we can do nearly everything that’s necessary with a declarative syntax. I don’t want to add a third config file that’s totally different to rtx.

My goal isn’t to replicate direnv. However I suspect the way people actually use direnv is for simple things that don’t require a DSL. I used direnv for a decade and I don’t think I ever used it for anything other than simple env vars and PATH modifications.

I think we can just target the most commonly used direnv pieces, make them possible in TOML, and we can solve these problems in a simpler way. If you want to define this stuff in bash then you should just use direnv.

**Comment by jdxcode** [comment]
for this use-case: `export PROJECT_NAME=$(basename $(pwd))`

I think we can add support for this just by adding templating support in env vars:

```toml
PROJECT_NAME="{{env.PWD}}"
```

**Comment by ericbn** [comment]
+1 on the idea of using a template language in .rtx.toml. I was going to propose using the bash variable expansion or even the zsh variable expansion syntax, which is a superset of the bash one. See https://hyperpolyglot.org/unix-shells#var-expansion.

Examples:
| Shell | Toml |
| --- | --- |
| `export PROJECT_NAME=$(basename $(pwd))` | `PROJECT_NAME = "${PWD:t}"` or `PROJECT_NAME = "$PWD:t"` (only available in zsh) |
| `export PATH="${PATH}:${PWD}/node_modules/.bin"` | `PATH = "${PATH}:${PWD}/node_modules/.bin"` |
| `export PATH="$PATH:$PWD/node_modules/.bin"` | `PATH = "$PATH:$PWD/node_modules/.bin"` |

Note that `$(basename $(pwd))` (or `$(basename $PWD)`)  is not the same as `$PWD`. This extract the last part of the path only (aka the tail).

**Comment by jdxcode** [comment]
making sure we hit all the bash rules I suspect will be challenging. A templating tool would allow complex logic like conditionals and loops as well.

**Comment by ericbn** [comment]
Cool. I was thinking of the bash/zsh syntax because that already covers common scenarios used in shell scripts. If the templating tool will allow even more than just [variable expansion](https://hyperpolyglot.org/unix-shells#var-expansion), then amazing!

I wonder if we could even rewrite the python layouts or others using the chosen template engine. Maybe this would allow having a builtin library of templates that users can pick from (instead of the current experimental `python = {virtualenv='venv'}`).
