### ISSUE TITLE
Add silent self-update

### ISSUE THREAD

**Issue by niccolomineo** [jdxcode/rtx#316]
It would be useful to allow passing some kind of flag to the `self-update` command, so that `rtx` could be put in a pipeline.

**Comment by jdxcode** [comment]
do you mean silent or not prompt? You can just run this:

```
yes | rtx self-update
```

**Comment by niccolomineo** [comment]
Completely silent would be better, but it's up to you.

**Comment by jdxcode** [comment]
you can just do this then:

```
yes | rtx self-update 2>&1 >/dev/null
```
