### ISSUE TITLE
Not property cleaning up environment variables between directory changes or looking up the directory structure

### ISSUE THREAD

**Issue by ericbn** [jdxcode/rtx#321]
**Describe the bug**
Not sure if rtx is not property cleaning up environment variables between directory changes, or looking **up** the directory structure for .rtx.toml files, which is unexpected.

**To Reproduce**
1. `cd $(mktemp -d)`
2. `echo -e 'export RTX_USE_TOML=1\nsource <(rtx activate zsh)' > .zshrc`
3. `echo -e '[tools]\npython = ["3.9", "3.8"]' > .rtx.toml`
4. `HOME=${PWD} exec zsh`
5. `rtx install`
6. `mkdir -p projects/project{1,2,3}`
7. `echo -e '[tools]\npython = {version="3.8", virtualenv="venv"}' > projects/project1/.rtx.toml`
8. `echo -e '[tools]\npython = {version="3.9", virtualenv="venv"}' > projects/project2/.rtx.toml`
9. `echo -e '[tools]\npython = {version="3.9", virtualenv="venv"}' > projects/project3/.rtx.toml`
10. `cd ~/projects/project1`
11. `cd ~/projects/project2`
12. `cd ~/projects/project3`
13. `cd ~/projects/`
14. `echo $PATH` -- PATH starts with `/tmp/projects/project3/venv/bin:/tmp/.local/share/rtx/installs/python/3.9.16/bin:/tmp/projects/project1/venv/bin:/tmp/.local/share/rtx/installs/python/3.8.16/bin:` followed by system path entries
15. `echo $VIRTUAL_ENV` -- VIRTUAL_ENV is `/tmp/projects/project3/venv`
10. `cd ~/projects/project1`
11. `cd ~/projects/project2`
13. `cd ~/projects/`
14. `echo $PATH` -- PATH starts with `/tmp/projects/project2/venv/bin:/tmp/.local/share/rtx/installs/python/3.9.16/bin:/tmp/projects/project1/venv/bin:/tmp/.local/share/rtx/installs/python/3.8.16/bin:` followed by system path entries
15. `echo $VIRTUAL_ENV` -- VIRTUAL_ENV is `/tmp/projects/project2/venv`
16. `cd /bin`
17. `echo $PATH` -- PATH does not contain any of the rtx-related entries.
18. `echo $VIRTUAL_ENV` -- VIRTUAL_ENV is not set

**Expected behavior**
When I'm at ~/projects, the PATH should not include `/tmp/projects/project1/venv/bin:`, `/tmp/projects/project2/venv/bin:` or `/tmp/projects/project3/venv/bin:`, and only start with `/tmp/.local/share/rtx/installs/python/3.9.16/bin:/tmp/.local/share/rtx/installs/python/3.8.16/bin:`. Likewise, VIRTUAL_ENV should not be set when I'm at ~/projects.

Also note that `/tmp/projects/project3/venv/bin:` seems to override `/tmp/projects/project2/venv/bin:` when actually none of them should be in the PATH after leaving the respective directories.

When I'm outside a directory that has a .rtx.toml file below or above it, the PATH and VIRTUAL_ENV are properly cleared from rtx-related entries, as expected.

**`rtx doctor` output**

```
rtx version:
  1.23.4 macos-x64 (built 2023-03-13)

shell:
  /usr/local/bin/zsh
  zsh 5.9 (x86_64-apple-darwin21.3.0)

rtx environment variables:
  RTX_SHELL=zsh
  RTX_USE_TOML=1

settings:
  {"experimental": "false", "missing_runtime_behavior": "prompt", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

config files:
  /tmp/.rtx.toml

plugins:
  python   https://github.com/jdxcode/rtx-python.git#5853786

toolset:
  python@3.9 python@3.8

No problems found
```

**Additional context**
I'm using zsh as shell.

EDIT: Updated to show that VIRTUAL_ENV is also affected.

**Comment by jdxcode** [comment]
I wasn't able to reproduce this. I'll try again tomorrow in a fresh docker container. I'm wondering if maybe you have something else that activated the venv or something.

**Comment by ericbn** [comment]
Hi. Thanks for checking. I was able to reproduce using this:

1. `docker pull archlinux:latest`
2. `docker run --rm -it archlinux sh`
3. `pacman -Sy`
4. `pacman -Sy base-devel gcc git zsh`
5. `curl https://rtx.pub/install.sh | sh`
6. `echo -e 'export RTX_USE_TOML=1\nsource <(/root/.local/share/rtx/bin/rtx activate zsh)' > .zshrc`
7. Continue at step 3 in the description.

**Comment by jdxcode** [comment]
I needed to use ubuntu since I'm on arm and I didn't want to wait forever for python to compile. In case I need these steps again:

```
finch run -it --rm ubuntu
apt update
apt install -y build-essential libssl-dev zlib1g-dev git zsh libffi-dev lzma-dev libreadline-dev libsqlite3-dev libncursesw5-dev liblzma-dev xz-utils libbz2-dev
cd
curl https://rtx.pub/install.sh | sh
echo -e 'export RTX_USE_TOML=1\nsource <(/root/.local/share/rtx/bin/rtx activate zsh)' > .zshrc
```

**Comment by ericbn** [comment]
Thanks a lot for being so quick in checking and fixing it!

**Comment by jdxcode** [comment]
the fix is awful though, I need to disable exec-env cache for _all_ python users, not just those using virtualenv functionality. This makes rtx way slower for python users. I will be thinking of a way to fix this. Ideally in a way that we could keep caching even for virtualenv users. I think we can keep caching so long as the directory doesn't change and the virtualenv config doesn't change.

**Comment by ericbn** [comment]
Better to be slower and correct (and most of the times this means being simpler too, which is great) than faster no matter what, right?  :- )

I actually didn't feel any noticeable speed difference between versions 1.23.7 and the previous one I was using.

<sub>My 2 cents: I totally sympathize with the need to optimize. There's a project I take care of for which we [removed a few optimizations](https://github.com/romkatv/zsh-bench/issues/5#issuecomment-1029519185) that were just unsafe or unreliable and didn't make any noticeable difference to our benchmarks. Those optimizations were there for ages. I guess the rule of thumb here is to benchmark before you optimize. Having the asdf and maybe asdf + direnv timings in the benchmark would serve as a good comparison. Just by using rust instead of bash you should already be way ahead!</sub>

**Comment by jdxcode** [comment]
I did benchmark it, and it now runs ~23ms if you have python plugins and ~15ms if you don't. 8ms isn't probably something you'd notice, but I still would very much like to fix this since these things can quickly add up.
