### ISSUE TITLE
rtx activate logging a lot to terminal and config not being respected

### ISSUE THREAD

**Issue by Maxssho13** [jdxcode/rtx#322]
**Describe the bug**
When rtx activate is ran, a lot of text is printed to the terminal. This happens on versions 1.23.4 and 1.23.5 but not on 1.23.3, all tested with the same config.
The following is what is printed after every new terminal instance(when rtx activate is ran): 
```
++ setup_virtualenv
++ local python_bin=/Users/glass/.local/share/rtx/installs/python/3.11.2/bin/python
+++ eval 'echo '
++++ echo
++ VIRTUAL_ENV=
++ '[' '' = '' ']'
++ return
++ setup_pipenv
++ local python_bin=/Users/glass/.local/share/rtx/installs/python/3.11.2/bin/python
+++ eval 'echo '
++++ echo
++ local pipfile=
++ '[' '' = '' ']'
++ return
+ export -p
```

**To Reproduce**
- `$ brew install jdxcode/tap/rtx`
- `$ echo 'rtx activate fish | source' >> ~/.config/fish/config.fish`
-  now whenever rtx activate is ran, like when a new terminal instance is created, a lot of text is printed to the terminal.

**Expected behavior**
Nothing should be printed

**`rtx doctor` output**

```
rtx version:
  1.23.5 macos-arm64 (built 2023-03-13)

shell:
  /usr/local/bin/fish
  fish, version 3.6.0

rtx environment variables:
  RTX_SHELL=fish

settings:
  {"experimental": "false", "missing_runtime_behavior": "prompt", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "verbose": "true", "asdf_compat": "false", "jobs": "1", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

config files:
  /Users/glass/.config/rtx/config.toml
  /Users/glass/.tool-versions

plugins:
  python   https://github.com/jdxcode/rtx-python.git#3d154f0

toolset:
  python@3.11.2

No problems found
```

**Additional context**
I'm not sure if this is the issue since I noticed the same behavior in version 1.23.3(when it was working as I expect) but the output of rtx doctor indicates that log level is set to info and raw is set to false, however in my root rtx config file(/Users/glass/.config/rtx/config.toml) which rtx doctor confirms is found, I have log_level set to "warn" and raw set to `true`.
Config file:
```toml
[settings]

log_level = "warn"
raw = true
```

**Comment by jdxcode** [comment]
this was fixed in https://github.com/jdxcode/rtx-python/pull/6
