### ISSUE TITLE
[WARN] Sending fatal alert BadCertificate

### ISSUE THREAD

**Issue by derkoe** [jdxcode/rtx#324]
**Describe the bug**
When running rtx 1.23.5 in Ubuntu it logs warnings like:
``` 
[WARN] Sending fatal alert BadCertificate
```

1.22.x does not seem to have this issue.

**To Reproduce**
Steps to reproduce the behavior.

1. `docker run -it --rm ubuntu`
2. `apt update && apt install git wget`
3. `wget https://github.com/jdxcode/rtx/releases/download/v1.23.5/rtx-v1.23.5-linux-x64`
4. `chmod +x rtx-v1.23.5-linux-x64`
5. `eval "$(./rtx-v1.23.5-linux-x64 activate bash)"`
6. `rtx version`

Output: 
```
root@c7c9392e1eed:/# rtx version
1.23.5 linux-x64 (built 2023-03-13)
[WARN] Sending fatal alert BadCertificate
```

**Expected behavior**
rtx should not log these warnings

**`rtx doctor` output**

```
rtx version:
  1.23.5 linux-x64 (built 2023-03-13)

shell:
  bash
  GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
  Copyright (C) 2020 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

rtx environment variables:
  RTX_SHELL=bash

settings:
  {"experimental": "false", "missing_runtime_behavior": "prompt", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

config files:

plugins:

toolset:


[WARN] Sending fatal alert BadCertificate
No problems found
```

**Additional context**

This only happens when your are behind an HTTPS intercepting proxy. The Certificate of the proxy is trusted via ca-certificates.

**Comment by derkoe** [comment]
Just found the exact version since this happens: v1.23.3

It might be the switch to rustls https://github.com/jdxcode/rtx/commit/a74ff740091586a18e807ca25aed4a519fca8942

**Comment by derkoe** [comment]
It seems that `rtx` is also making a network call to `rtx.pub` on every call of a shim

```
❯ .rtx/shims/npm -v
[WARN] Sending fatal alert BadCertificate
9.5.0
```

**Comment by jdxcode** [comment]
fixed in https://github.com/jdxcode/rtx/commit/9b3dff4d917d66dd50a37dedb7feafcdd64280b2

**Comment by derkoe** [comment]
Thx!
This would be a solution with https - https://docs.rs/rustls-native-certs/latest/rustls_native_certs/

**Comment by jdxcode** [comment]
thanks for that! I have some plans to do runtime fetching inside of rtx. If I implement that I'll definitely need this.

**Comment by derkoe** [comment]
Just have to activate the feature: `rustls-tls-native-roots`
https://docs.rs/reqwest/latest/reqwest/#optional-features
