### ISSUE TITLE
rtx global --install-missing has unintuitive behavior

### ISSUE THREAD

**Issue by dsully** [jdxcode/rtx#327]
**Describe the bug**
My expectation from reading #188 and the PR for #263 is that `rtx global --install-missing` would install any missing tools that are defined in `~/.tool-versions` or `$XDG_CONFIG/rtx/config.toml`

However, that is not the case as shown below.

If I set `RTX_MISSING_RUNTIME_BEHAVIOR=autoinstall`, then the rtx shell hook immediately kicks off an install, which is expected. But also not the explicit behavior I thought `--install-missing` was supposed to provide.

**To Reproduce**
```
[WARN] Tools not installed: python@3.10, python@3.11   
[~] (master *) 
$ rtx global --install-missing 
[tools]
python = [ '3.10', '3.11' ]
[~] (master *)
$ rtx global python --install-missing
3.10 3.11
[~] (master *)
$ rtx global python@3.10 --install-missing
rtx python https://github.com/jdxcode/rtx-python.git#5853786
Downloading Python-3.10.10.tar.xz...
-> https://www.python.org/ftp/python/3.10.10/Python-3.10.10.tar.xz
Installing Python-3.10.10...
```

Maybe I'm "holding it wrong" ? I also realize that last command is explicitly installing the version of Python, so `--install-missing` would really have no effect anyways.

**`rtx doctor` output**

```
$ rtx doctor
rtx version:
  1.23.5 linux-x64 (built 2023-03-13)

shell:
  /usr/bin/fish
  fish, version 3.6.0

rtx environment variables:
  RTX_SHELL=fish
  RTX_USE_TOML=1
  RTX_EXPERIMENTAL=1

settings:
  {"experimental": "true", "missing_runtime_behavior": "prompt", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

config files:
  /home/dsully/.config/rtx/config.toml

plugins:
  python   https://github.com/jdxcode/rtx-python.git#5853786

toolset:
  python@3.10 python@3.11

No problems found
```

**Comment by jdxcode** [comment]
for now as a workaround you can use `rtx i --install-missing && rtx global` to get the behavior you're looking for
