### ISSUE TITLE
templating in env vars

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#332]
for this use-case: `export PROJECT_NAME=$(basename $(pwd))`

I think we can add support for this just by adding templating support in env vars:

```toml
[env]
PROJECT_NAME="{{env.PWD}}"
```

we don't have this now, but it's easy to add and I think useful for a lot of things

_Originally posted by @jdxcode in https://github.com/jdxcode/rtx/issues/310#issuecomment-1470188897_

**Comment by jdxcode** [comment]
only thing is: you don't actually want $PWD here, you want the directory the `.rtx.toml` is in. In plugins this is supported with `RTX_PROJECT_ROOT` which points to that directory. We can probably expose that here as well.

**Comment by jdxcode** [comment]
https://tera.netlify.app/ looks like my favorite for templating support from a short look around at the options in rust. Handlebars and liquid are also popular, but I don't think it's important to subscribe to any particular format.

**Comment by delicb** [comment]
I have just tried this and it works great. 

Actual expression I used was `PROJECT_NAME = "{{config_root | split(pat='/') | last}}"`, since, by convention, project name is the name of the folder where `.rtx.toml` is, and templating supports all builtin filters from `tera`. This is awesome :)

**Comment by jdxcode** [comment]
wow I'm a little surprised it supports all of that!

**Comment by delicb** [comment]
I was as well, this is the first time I am using `tera`, but it based on `Jinja2` and `Django` templates, which I have know well, so I have expected something similar. 

This opens up a lot of possibilities IMO, especially in combination with ability to register custom filter and functions that can be invoked in template. Not that a use case comes to mind right now, but when it does, it is great that it can be added :)

**Comment by delicb** [comment]
Btw, while having `env` in context make things easier, it is not strictly required, since `tera` has `get_env` function, which could be used like `LD_LIBRARY_PATH = "/some/path:{{get_env(name='LD_LIBRARY_PATH')}}"`

**Comment by jdxcode** [comment]
good to know! I'm a little scared of just how much functionality I unintentionally introduced haha

**Comment by jdxcode** [comment]
`LD_LIBRARY_PATH = "/some/path:{{get_env(name='LD_LIBRARY_PATH')}}"`

this is a bit dangerous after thinking about it since it's not using the "pristine" environment (which strips away rtx env vars). If you attempt to use env vars that rtx provides (like PATH) I have no idea what will happen, but it probably won't be consistent.

I was thinking that aliases might be one place we could use templates. It might have made it so we didn't need to implement "latest!-1"—though that may have required a lot of tera logic if it's even possible.

**Comment by jdxcode** [comment]
OK I added this for a bunch more things including the entire .tool-versions file and most of .rtx.toml. I even added an `exec()` function to run subcommands. Seems like this could solve a ton of problems people may have.

**Comment by delicb** [comment]
Hm, I am not sure `exec` is a good idea right now. I can imagine cloning a repo that has `.rtx.toml` with `exec(command="rm -rf")` in it :/. Direnv has `direnv allow` because of that. I do think it is useful, but maybe there should be similar security mechanism like for direnv?

**Comment by delicb** [comment]
On the other hand - I like the power coming with `exec` and ease of use that does not require explicit `allow`. Maybe adding check to [this](https://github.com/jdxcode/rtx/blob/main/src/tera.rs#L21) function and enforcing security model here only? So if dangerous function (like `exec` and maybe other is the future) is used without doing something like `rtx allow`, warning would be printed and `exec` would not run. 

Just a thought, looks to me like a good balance between ease of use and powerfulness, but I do believe that some mechanism to prevent automatic execution is needed with `exec` being introduced.

**Comment by jdxcode** [comment]
I think what we need to do is something a little bit like [deno](https://deno.land/manual@v1.31.3/basics/permissions)'s permissions model. *Dangerous* things like modifying env vars or running `exec()` would error out if a given file tries to do something you haven't whitelisted.

That way we wouldn't need to approve every single .rtx.toml, just the ones that do potentially dangerous actions.

**Comment by jdxcode** [comment]
That said, if someone wanted to be truly malicious there are probably a lot of vectors here. Here's another I just thought of:

```toml
[tools]
some_malicioud_thing = 'path:./malicious_plugin'
```

That'll run `./malicious_plugin/bin/exec-env` automatically when you enter the directory if it exists

**Comment by jdxcode** [comment]
On second thought, I'm not sure we need granularity here. It's probably sufficient to mark an `.rtx.toml` as "trusted" or "untrusted".
