### ISSUE TITLE
Help Request: Evaluate String Output From External Program In Hook

### ISSUE THREAD

**Issue by toadslop** [jdxcode/rtx#334]
According to the hooks documentation, you can evaluate a string as a nushell script. This works.
I have an application that I want to call from a hook. This app returns a nushell script as a string.
I want to evaluate and execute that string.
How can I do this?

**Comment by jdxcode** [comment]
I'm not sure what you're talking about at all, is this the right project?

**Comment by toadslop** [comment]
Hi @jdxcode , you're right. Sorry about that. I had two github browser tabs open and I accidentally typed this in the wrong one.
