### ISSUE TITLE
.rtx.toml to handle envs if it depends on multiple values?

### ISSUE THREAD

**Issue by yssource** [jdxcode/rtx#335]
1. How to set env variable with multiple values?
error log, `.rtx.toml expected value of "env" to be a string, got:  [`

I wanna set LD_LIBRARY_PATH, which looks like it in .envirc 
`export LD_LIBRARY_PATH="${PROJECT_HOME}/lib:~/.local/share/lib:.lib:${LD_LIBRARY_PATH}"`
```
[env]
LD_LIBRARY_PATH = [
# depends on another variable
"${PROJECT_HOME}/lib",
  # adds an absolute path
  "~/.local/share/lib",
  # adds a path relative to the directory this config is in, not necessarily PWD
  "./lib",
  "$LD_LIBRARY_PATH" # required to be at the end
]
```
2. How to set env variable with another env variable in .rtx.toml?
if `LD_LIBRARY_PATH` depends on `${PROJECT_HOME}`
`export LD_LIBRARY_PATH="${PROJECT_HOME}/lib`

Thanks.

**Comment by jdxcode** [comment]
This isn't currently possible
