### ISSUE TITLE
brew upgrade failing with 522 server error

### ISSUE THREAD

**Issue by delicb** [jdxcode/rtx#338]
Please see attached screenshot.

![SCR-20230317-gsx](https://user-images.githubusercontent.com/131180/225888384-f709ca68-e980-4299-8d8d-c568fd317d10.png)

**Comment by aleksandarristic** [comment]
I have the same problem. When I try navigating to the download link in browser, I get an error from Cloudflare:

<img width="1041" alt="Screenshot 2023-03-17 at 14 19 06" src="https://user-images.githubusercontent.com/993080/225916327-23761d19-f3aa-4ecb-b888-9653e0a4085c.png">

I can see that the package I'm trying to download is accessible via github release page (https://github.com/jdxcode/rtx/releases/download/v1.23.8/rtx-v1.23.8-macos-x64.tar.gz), but the rtx.pub link doesn't work, so update via homebrew is not possible.

**Comment by jdxcode** [comment]
I changed some things around with s3 and forgot a step, should hopefully be working in the next release which is going out now

**Comment by jdxcode** [comment]
at first cloudflare wasn't working for me, but I purged the entire cache and now it seems to be working. lmk if anyone is seeing problems here

**Comment by aleksandarristic** [comment]
Works for me now. Wasn't working 15 minutes ago. Seems that the cache purge has done it. Thanks!

**Comment by delicb** [comment]
I confirm that it is working for me as well, just upgraded to `1.23.10`.

**Comment by jdxcode** [comment]
sorry for the trouble! I switched to cloudflare's r2 from s3 because I just wanted to consolidate everything under cloudflare, but I couldn't get r2 to work with http (non-ssl) _at all_ so I switched the assets back to s3

**Comment by jdxcode** [comment]
cloudflare seems super buggy generally, not very happy with it so far
