### ISSUE TITLE
Error with Fish Shell and Python

### ISSUE THREAD

**Issue by CrshOverride** [jdxcode/rtx#362]
**Describe the bug**
I have a clean setup of `rtx` (from the custom Homebrew tap). I had a previous global python version set with `asdf`. Immediately upon installing the proper version of python (and ensuring that my shell config was properly updated), I was given the following warnings:

```sh
[WARN] Error running exec-env: command ["bash", "-c", ". /Users/justin.niessner/.local/share/rtx/plugins/python/bin/exec-env\nexport -p\n"] exited with code 1
[WARN] Error listing bin paths for python@3.11.2: command ["bash", "-c", ". /Users/justin.niessner/.local/share/rtx/plugins/python/bin/exec-env\nexport -p\n"] exited with code 1
```

I have verified that there is no `python` in the path and `python3` still points to the Homebrew version previously installed.

**To Reproduce**
```fish
brew install jdxcode/tap/rtx; \
and echo 'rtx activate fish | source' >> ~/.config/fish/config.fish; \
and source ~/.config/fish/config.fish; \
and rtx install python 
```

**Expected behavior**
No warnings are shown and both `python` and `python3` point to the `rtx` managed bins.

**`rtx doctor` output**

```
rtx version:
  1.25.5 macos-arm64 (built 2023-03-19)

shell:
  fish
  fish, version 3.6.0

rtx environment variables:
  RTX_SHELL=fish

settings:
  {"experimental": "false", "missing_runtime_behavior": "prompt", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

config files:
  /Users/justin.niessner/.tool-versions

plugins:
  nodejs   https://github.com/jdxcode/rtx-nodejs.git#a9af74f
  python   https://github.com/jdxcode/rtx-python.git#d0611d0

toolset:
  python@3.11.2

No problems found
```

**Additional context**
I also upgraded `bash` to the latest version available on Homebrew to eliminate that as a potential cause.

**Comment by jdxcode** [comment]
sorry about this, it should be fixed if you update python with `rtx plugins update python`

**Comment by CrshOverride** [comment]
@jdxcode Confirmed as fixed. Thanks for the update.
