### ISSUE TITLE
rtx upgrade golang and reinstall all installed exe

### ISSUE THREAD

**Issue by wacdev** [jdxcode/rtx#377]
as title

I found when I upgrade golang , the installed exe all loss

**Comment by jdxcode** [comment]
I have no clue what you're asking me. Maybe try an example or something.

**Comment by wacdev** [comment]
this my script , I want can auto run this when golang updated

Otherwise, every time I upgrade, the tools I installed will be gone. My vim plug-ins depend on these tools, and it is very troublesome to run them manually. Or if there is a way to hook my script to run.

```
❯ cat go.install.txt
github.com/louisun/heyspace
mvdan.cc/sh/v3/cmd/shfmt
❯ cat go.install.backup.sh
#!/usr/bin/env bash

DIR=$(realpath $0) && DIR=${DIR%/*}
cd $DIR

GOPATH=${GOPATH:-"$HOME/go"}
BIN_PATH="$GOPATH/bin"
OUTPUT_FILE="go.install.txt"

>$OUTPUT_FILE

for file in $(ls $BIN_PATH); do
  module_info=$(go version -m $BIN_PATH/$file 2>/dev/null | grep '^\s*path' | awk '{print $2}')
  echo "$module_info" >>$OUTPUT_FILE
done

cat $OUTPUT_FILE
❯ cat go.install.sh
#!/usr/bin/env bash

DIR=$(realpath $0) && DIR=${DIR%/*}
cd $DIR

INPUT_FILE="go.install.txt"

if [ ! -f "$INPUT_FILE" ]; then
  echo "$INPUT_FILE NOT EXIST"
  exit 1
fi

while IFS= read -r line; do
  cmd="go install $line@latest"
  echo $cmd
  eval $cmd
done <$INPUT_FILE
```

**Comment by jdxcode** [comment]
ah I think this is what you're looking for: https://github.com/kennyp/asdf-golang#default-go-get-packages

**Comment by wacdev** [comment]
Thanks, works.

But it would be nice if there was a command line option to automatically create this .default-golang-pkgs file on upgrade.
