### ISSUE TITLE
Global Python version preceding Python venv 

### ISSUE THREAD

**Issue by hermanocabral** [jdxcode/rtx#383]
**Describe the bug**
On a  fresh install of RTX using homebrew, when you have a global version of python it takes precedence over virtualenv once you activate it.

What happens:
```PATH=/Users/randomuser/.local/share/rtx/installs/go/1.20.2/go/bin:/Users/randomuser/.local/share/rtx/installs/go/1.20.2/packages/bin:/Users/randomuser/.local/share/rtx/installs/python/3.11.2/bin:/Users/randomuser/.local/share/rtx/installs/nodejs/18.15.0/bin:/Users/randomuser/dev/test/venv/bin:/Users/randomuser/Library/.......```

What was expected:
```PATH=/Users/randomuser/dev/test/venv/bin:/Users/randomuser/.local/share/rtx/installs/go/1.20.2/go/bin:/Users/randomuser/.local/share/rtx/installs/go/1.20.2/packages/bin:/Users/randomuser/.local/share/rtx/installs/python/3.11.2/bin:/Users/randomuser/.local/share/rtx/installs/nodejs/18.15.0/bin:/Users/randomuser/Library/.......```

**To Reproduce**
Assuming you installed RTX using Homebrew and installed a version of Python:
1. Create a folder: ```mkdir tmp-rtx-venv```
2. Create a python virtual environment: ```python -m venv .venv``` 
3. Set a global Python version: ```rtx global python 3.11.2```
4. Make a note of your current path. I'm using fish so I run ```env``` to dump all the variables.
5. Make a note of which python: ```which python```
6. Activate the python virtual environment: ```source .venv/bin/activate.fish``` (for the fish shell, for others please adjust)
7. Recheck your PATH and python: ```env && which python```

**Expected behavior**
Virtualenv path would be prepended to the PATH (eg. PATH = VENV_PATH + PATH) variable. Right now it's being added but the GLOBAL RTX config takes priority (eg. PATH = GLOBAL_RTX + VENV_PATH + PATH)

**`rtx doctor` output**

```
rtx version:
  1.26.2 macos-arm64 (6fbbcd3 2023-03-23)

build:
  Target: aarch64-apple-darwin
  Features: BREW
  Built: Thu, 23 Mar 2023 13:13:46 +0000
  Rust Version: rustc 1.67.1 (d5a82bbd2 2023-02-07)
  Profile: release

shell:
  /opt/homebrew/bin/fish
  fish, version 3.6.0

rtx environment variables:
  RTX_SHELL=fish

settings:
  {"experimental": "false", "missing_runtime_behavior": "prompt", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

config files:
  /Users/$$$$/.tool-versions

plugins:
  go       https://github.com/kennyp/asdf-golang.git#f006a12
  nodejs   https://github.com/jdxcode/rtx-nodejs.git#a9af74f
  python   https://github.com/jdxcode/rtx-python.git#e21a6da

toolset:
  go@1.20.2, python@3.11.2, nodejs@18.15.0

No problems found
```

**Additional context**

**`rtx ls` output**
```
⏵  go 1.20.2                 (set by ~/.tool-versions)
⏵  nodejs 18.15.0            (set by ~/.tool-versions)
⏵  python 3.11.2             (set by ~/.tool-versions)
```

**`which python` output**
```
/Users/randomuser/local/share/rtx/installs/python/3.11.2/bin/python
```

**Comment by jdxcode** [comment]
you can either set the version to "system" with `rtx local python@system` or you can use the [experimental virtualenv](https://github.com/rtx-plugins/rtx-python#experimental-virtualenv-support) support built into rtx

**Comment by hermanocabral** [comment]
Just tested and it works fine with the experimental virtualenv support. I'm assuming this is the way forward for venvs & rtx?

**Comment by jdxcode** [comment]
yeah that's what I would do
