### ISSUE TITLE
rtx activate network timeout too long

### ISSUE THREAD

**Issue by pzcfg** [jdxcode/rtx#394]
**Describe the bug**
Under certain unreachable network conditions (described below) `rtx activate` will block and prevent the shell from being usable for 75 seconds (!!)

https://user-images.githubusercontent.com/94077014/227620644-23c6937d-ac6e-4439-a28c-fb3b1e35148a.mp4

**To Reproduce**
I'm not 100% sure what the conditions are here, but I think this happens on most/any captive wifi, or any network where the response waits indefinitely vs being immediately closed.

I think you may also need to be in state where it needs to update but hasn't? 

- Setup yarn plugin (not sure if this is an issue with others, but it's the first error mine fails with)
- Connect to / setup aforementioned network condition
- Add `eval "$(rtx activate -qs zsh)"` to `.zshrc` (or equivalent for your shell of choice)
- Open a new shell

**Expected behavior**
After not being able to reach the server within a few seconds, error out and allow the shell to be used

**Comment by jdxcode** [comment]
it does check for updates once per week, you can force it by running `rtx cache clean`. I'm going to try using the apple network link conditioner to simulate a bad connection. There is a short timeout on this so it shouldn't hang for that long.

**Comment by jdxcode** [comment]
you're right, this is hanging [despite the timeout being set](https://github.com/jdxcode/rtx/blob/4277741e0a9e08d3725cb91e93ed4f4c481ca1cd/src/cli/version.rs#L117).

**Comment by jdxcode** [comment]
weird, it seems that the issue is that I put the timeout on the _client_ and not the _request_. The request does actually time out in the logs, but reqwest just doesn't do anything afterwards. Feels like a reqwest bug to me.

**Comment by pzcfg** [comment]
I think mine may (also?) be hanging/timing out on this git command in the [list-all](https://github.com/twuni/asdf-yarn/blob/main/bin/list-all) script for [twuni/asdf-yarn](https://github.com/twuni/asdf-yarn). I'm wondering if whatever spawns the script execution needs a timeout for receiving output and/or completing running.

**Comment by jdxcode** [comment]
yeah I'll leave this open to think about that. It's more complicated though since I'm not sure how long to wait. I think in the case of activate it actually shouldn't be executing that at all so long as it has _some_ cache to use. That actually should be the current behavior but something must not be working right.

There are other cases like `rtx i` where we need the output of that, but a timeout of like 30 seconds is probably plenty of time to give it.

**Comment by jdxcode** [comment]
actually I'm going to open a separate issue since this is kind of a different thing

**Comment by jdxcode** [comment]
it might not be immediately obvious why this is related but the ticket is here:

https://github.com/jdxcode/rtx/issues/402

Essentially the idea is that things should be rearchitected such that there isn't a need to call list-all during hook-env at all.
