### ISSUE TITLE
Suggestion: Add rtx to rbenv wiki comparison page

### ISSUE THREAD

**Issue by jordan-brough** [jdxcode/rtx#4]
Just a suggestion: It could be good for visibility to add rtx to this page?

https://github.com/rbenv/rbenv/wiki/Comparison-of-version-managers

**Comment by jdxcode** [comment]
You're part of the very first round of users so there are definitely some bugs to iron out but promoting generally it is a great idea. I also found [this for .node-version](https://github.com/shadowspawn/node-version-usage) which would be a great place to present it.

Hopefully I can get these bugs you and other have found all resolved by the end of the weekend.

**Comment by jdxcode** [comment]
I'm going to close since this is really a better question for rbenv. and @mislav If you want to make a request for that wiki page in particular I would open a ticket on rbenv.

I might suggest adding the section right below asdf which would be something like the following:

> ## rtx
> rtx is another multi-language version manager that works as a drop-in replacement for asdf which doesn't have the same performance issues as asdf. It's a new project that's under rapid development.

**Comment by mislav** [comment]
Added! Thanks
