### ISSUE TITLE
asdf-java issues

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#403]
Now that I've forked asdf-java into rtx-java, there are a few fixes I want to make:

- [x] ~support installing intel JVMs via rosetta (add `RTX_ARCH` env var to call plugins with `arch -x86_64`) https://github.com/halcyon/asdf-java/issues/173~ created #405 for this one
- [x] fix `.asdf/lib/utils.bash: No such file or directory` error (appears to be cosmetic)
- [x] change "default" java to openjdk (I'm not a java dev, so tell me if this is a bad idea) https://github.com/halcyon/asdf-java/issues/190

Issues that will be fixed by these tasks:
* https://github.com/halcyon/asdf-java/issues/201
* https://github.com/halcyon/asdf-java/issues/193
* https://github.com/halcyon/asdf-java/issues/202
* https://github.com/halcyon/asdf-java/issues/188
* https://github.com/halcyon/asdf-java/issues/182
* https://github.com/halcyon/asdf-java/issues/178
* https://github.com/halcyon/asdf-java/issues/177
* https://github.com/halcyon/asdf-java/issues/170
* https://github.com/halcyon/asdf-java/issues/169
* https://github.com/halcyon/asdf-java/issues/160
* https://github.com/halcyon/asdf-java/issues/156
* https://github.com/halcyon/asdf-java/issues/154
* https://github.com/halcyon/asdf-java/issues/152
* https://github.com/halcyon/asdf-java/issues/150
* https://github.com/halcyon/asdf-java/issues/149
* https://github.com/halcyon/asdf-java/issues/132
* https://github.com/halcyon/asdf-java/issues/131
* https://github.com/halcyon/asdf-java/issues/117

**Comment by jdxcode** [comment]
note that as of this writing the default plugin for java in rtx is still `asdf-java`. When I cut the next release the new default will be `rtx-java`, but if you already have the plugin installed that won't change. If you want these fixes, you'll need to do `rtx plugin uninstall java && rtx plugin install java`

**Comment by arthurqueiroz4** [comment]
error in show java versions 

arthur@arthur-IdeaPad-3-15ALC6:~$ asdf plugin-add java https://github.com/halcyon/asdf-java.git
arthur@arthur-IdeaPad-3-15ALC6:~$ asdf list all java
No compatible versions available (java )
arthur@arthur-IdeaPad-3-15ALC6:~$ asdf list-all java
No compatible versions available (java )

**Comment by jdx** [comment]
??
