### ISSUE TITLE
Multiple dotenv files

### ISSUE THREAD

**Issue by delicb** [jdxcode/rtx#418]
`dotenv` support in `.rtx.toml` is great. I still have one thing missing to completely replace `direnv` and that is ability to load environment from parent folder. 

In `direnv` I usually add `source_up` or `source_up_if_exists` in `.envrc` and in parent folder I have environment variables that are used for all project in that folder structure (e.g. `GIT_AUTHOR_NAME`, `GIT_AUTHOR_EMAIL`, `AWS_PROFILE`, etc). I actively have two folder structures structures with different project and different values for these variables. 

One idea is to simulate `source_up` by having `dotenv` accept list of paths and setting it to something like `dotenv = [".env", "../.env"]`. Simple string could continue working, in case there is only one `dotenv` file. I am not sure if relative path is a good idea here. I am ok with other solutions as well and I can follow up if I think of something else, just wanted to put this out there to start discussion.

**Comment by jdxcode** [comment]
you should be able to just put a `.rtx.toml` file in each directory. If everything is working right it should merge them.

**Comment by delicb** [comment]
Oh, nice, I wasn't aware of this. Awesome, thanks and sorry for the ticket.
