### ISSUE TITLE
Suggestion for better fish install

### ISSUE THREAD

**Issue by lpar** [jdxcode/rtx#419]
Rather than 

```
echo '~/bin/rtx activate fish | source' >> ~/.config/fish/config.fish
```

I think a better option would be

```
rtx activate fish > ~/.config/fish/conf.d/rtx.fish
```

The `conf.d` files are executed before `config.fish`, but looking at the output of `rtx activate fish` I don't see anything that relies on the rest of my environment being set up.

**Comment by Nick1296** [comment]
Maybe an unrelated problem, but `rtx activate fish` just prints script instead of executing it

**Comment by Nick1296** [comment]
This is what happens on my end, I installed rtx from cargo. Is it possible that I am doing something wrong with fish? I am fairly new on this shell... 

<img width="755" alt="Screenshot_40" src="https://user-images.githubusercontent.com/26071946/236925531-bcce78a9-d0ef-4b07-ad2b-45fd17d69e9e.png">

**Comment by lithammer** [comment]
That's expected. It's the same for all shells. You have to source/eval the output (or pipe it to something like `~/.config/fish/conf.d/rtx.fish` suggested by this issue). It's mentioned in at least two places in the readme.

**Comment by jdxcode** [comment]
oh I actually misread the issue, I actually think it's a bad idea. I could get behind doing this:

```
echo "rtx activate fish" > ~/.config/fish/conf.d/rtx.fish
```

however executing that and placing the results into an rtx.fish file would be a bad idea. If you do that, and the activation script changes, you won't get any updates and probably encounter strange bugs in the future.

**Comment by Nick1296** [comment]
I think I got around it by doing `rtx activate fish | source ` the doctor does not detect any problems and I managed to replicate the demo in the readme, thanks for the help!
