### ISSUE TITLE
Fails to install hadolint package

### ISSUE THREAD

**Issue by pedropombeiro** [jdxcode/rtx#42]
I have `hadolint v2.10.0` on my `~/.tool-versions` file. When I run `rtx install` it stops midway due to:

```
rtx: Installing runtime: hadolint@v2.10.0
* Downloading hadolint release v2.10.0...
curl: (22) The requested URL returned error: 404
asdf-hadolint: Could not download https://github.com/hadolint/hadolint/releases/download/vv2.10.0/hadolint-Darwin-x86_64
rtx: error command ["/Users/pedropombeiro/.local/share/rtx/plugins/hadolint/bin/download"] exited with code 1
rtx: Run with RTX_DEBUG=1 for more information.
```

It looks like it doesn't like the `v` prefix in the version, but `asdf` wants it. It would be nice to have this working so that it is possible to run `asdf` and `rtx` on the same project (different team members can have different preferences).

**Comment by jdxcode** [comment]
asdf doesn't seem to require the `v`:

```
❯ echo 'hadolint 2.10.0' >> .tool-versions

~
❯ asdf install hadolint
* Downloading hadolint release 2.10.0...
hadolint 2.10.0 installation was successful!
hadolint 2.10.0 is already installed
```

I could also strip `v` as any prefix but I'm worried that might have unintended consequences down the road. I think for now the best solution is not to use `v` in `.tool-versions`.

**Comment by pedropombeiro** [comment]
@jdxcode I don't know if at one point the `asdf list all hadolint` returned versions with the `v` prefix, which is how that got into my `.tool-versions` file. Nowadays that seems to be fixed, so I would say we can close this.
