### ISSUE TITLE
rtx-nodejs ideas

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#422]
I've got a couple of ideas for rtx-nodejs (or possibly rtx-npm,pnpm,yarn,bun).

* automatically alias `npm` to use pnpm, bun, or yarn. I was thinking today that I often default to running `npm install` even in projects that could benefit from a much faster installer. If I had a way to automatically use an alternative when in a directory I think that would help me still be able to use `npm install` but have it actually use something else under the hood.
* add `./node_modules/.bin` to PATH

**Comment by jdxcode** [comment]
for the automatic activating... I'm thinking that might work pretty well. I can just look if there is a yarn.lock, pnpm-lock.yaml, or package-lock.json to know which one to pick. Bun is a little harder since it keeps its lockfile around but still might work with `bun.lockb`.

**Comment by jdxcode** [comment]
`./node_modules/.bin` is fairly easy, though of limited utility since you can already just do this:
```toml
env_path = [
  './node_modules/.bin'
]
```

Still, I think it's worth abstracting this even though it'll be nearly the same amount of code. If for no other reason than it tells developers this is something they _should consider_ doing. Otherwise it would be harder to discover. My current thinking is adding the following option:

```toml
nodejs = {version='lts', node_modules_bin=true}
```

**Comment by jdxcode** [comment]
I discovered [ni](https://github.com/antfu/ni) which might be a better solution here than what I proposed for automatic activating at least.

**Comment by dpassen** [comment]
Was `node_modules_bin` ever implemented? Is it still planned?
