### ISSUE TITLE
The system-rust cargo packages bin dir is not added to PATH by the default rtx activation (should it be?)

### ISSUE THREAD

**Issue by AndydeCleyre** [jdxcode/rtx#427]
**Describe the bug**

Hello! While rtx adds some folders to `PATH` as expected, it does not add `~/.local/share/rtx/installs/rust/system/bin`, which I need to add manually. Is this expected, or a bug? I can justify either answer.

**To Reproduce**

I'm using rtx on Pop OS 22.04, with `~/.tool-versions`:

```
python system
nodejs latest
rust   system
elm    latest
```

```console
$ rtx current
python system
nodejs 19.8.1
rust system
elm 0.19.1

$ which cargo
/usr/bin/cargo
```

In my `.zshrc`, I activate rtx with

```shell
if (( $+commands[rtx] )) {
  eval "$(rtx activate zsh)"
  if [[ ! -r ${XDG_DATA_HOME:-~/.local/share}/zsh/site-functions/_rtx ]]  rtx complete -s zsh >${XDG_DATA_HOME:-~/.local/share}/zsh/site-functions/_rtx
}
```

Now when I install packages with `cargo`, I expected the binaries to end up in `~/.cargo/bin`, but they are instead at `~/.local/share/rtx/installs/rust/system/bin`. That's fine, but then I wonder if that should get automatically prepended to the PATH, which it currently is not:

```console
$ print -rl $path
/home/andy/.local/share/rtx/installs/nodejs/19.8.1/bin
/home/andy/.local/share/rtx/installs/elm/0.19.1/bin
/home/andy/.local/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/snap/bin
/usr/lib/execline/bin
```

**Expected behavior**

I expected `~/.local/share/rtx/installs/rust/system/bin` to be added to my `PATH` by the rtx activation step.

But I don't know for sure if that's expected, as it's not a path to `rustc` or `cargo` itself.

**`rtx doctor` output**

```
rtx version:
  1.27.9 linux-x64 (a5246dc 2023-03-27)

build:
  Target: x86_64-unknown-linux-gnu
  Features: DEB
  Built: Mon, 27 Mar 2023 15:52:08 +0000
  Rust Version: rustc 1.68.0 (2c8cc3432 2023-03-06)
  Profile: release

shell:
  /usr/bin/zsh
  zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

rtx environment variables:
  RTX_SHELL=zsh

settings:
  {"experimental": "false", "missing_runtime_behavior": "prompt", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "trusted_config_paths": "[]", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

config files:
  /home/andy/.tool-versions

plugins:
  elm      https://github.com/asdf-community/asdf-elm.git#df378ce
  nodejs   https://github.com/asdf-vm/asdf-nodejs.git#644ada3
  python   https://github.com/jdxcode/rtx-python.git#d7ea40b
  rust     https://github.com/code-lever/asdf-rust.git#0c88f99

toolset:
  python@system, nodejs@latest, rust@system, elm@latest

No problems found
```

**Comment by jdxcode** [comment]
> `~/.local/share/rtx/installs/rust/system/bin`

I think you're misunderstanding the point of "system". That is for using a version of rtx installed on your system that was _not_ provided by rtx.

**Comment by AndydeCleyre** [comment]
Yes, assuming one of those times you say "rtx" you mean "rust or whichever runtime," I am expecting to use the rustc and cargo installed via apt. But the tools I install with cargo end up in that rtx folder. Is that intentional?

**Comment by jdxcode** [comment]
I don't see how that could happen. If I set rust to system in a vanilla alpine install it sets no env vars that would modify how cargo works:

```
/ # rtx x rust@system -- env
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
RTX_MISSING_RUNTIME_BEHAVIOR=warn
```

**Comment by AndydeCleyre** [comment]
Yes I was surprised as well. I can take a closer look at everything in a couple of hours, but AFAIK I'm not setting any rtx/rust/cargo vars manually, and I have no rtx-installed rust/cargo runtimes.

**Comment by jdxcode** [comment]
My best guess is you were on an old version where there was a bug with system

**Comment by AndydeCleyre** [comment]
Yes, seems to be all well now, I just

```console
$ rm -rf ~/.local/share/rtx/installs/rust
$ rtx install  # nothing to install
$ cargo install ...
```

And this time `~/.cargo` was created and populated, instead of `~/.local/share/rtx/installs/rust`. I'm happy to see this closed as irrelevant for the current release, if you don't think it merits any further investigation.

Thanks!
