### ISSUE TITLE
Upgrading rtx (via Homebrew) causes hook issue in fish.

### ISSUE THREAD

**Issue by dsully** [jdxcode/rtx#433]
**Describe the bug**
When `rtx` is upgraded (in my case via Homebrew), the executable path is encoded pointing to the now non-existent version.

After the upgrade, fish spews this error:

```
$ echo

/home/linuxbrew/.linuxbrew/Cellar/rtx/1.27.9/bin/rtx: command not found
- (line 21):
    /home/linuxbrew/.linuxbrew/Cellar/rtx/1.27.9/bin/rtx hook-env -s fish | source;
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
in function '__rtx_env_eval'
in event handler: handler for generic event 'fish_prompt'
$
```

This appears to be due to he executable path being compiled into `fn activate(&self, exe: &Path, status: bool) -> String {` in `src/shell/fish.rs`

Not quite sure what the best way to address this is. You could detect a Homebrew path and point to the corresponding `$root/bin/` instead of the per-version path. Or perhaps running `rtx deactivate` as part of a pre-flight before installing the new version in the Homebrew formula?

**To Reproduce**
Upgrade `rtx` using Homebrew.

**Expected behavior**
No shell errors.

**Comment by jdxcode** [comment]
Upgrading rtx while it's activated is not a supported use-case. If the version changes, then you need to restart your shell.
