### ISSUE TITLE
Pin External Plugins

### ISSUE THREAD

**Issue by dbready** [jdxcode/rtx#446]
Unless I missed it, the `.rtx.toml` format lets you specify an external repository, and will always pull from HEAD. This strikes me as a potential supply-chain vulnerability if there is no way to lock to a known good version of the tooling.

Default, unspecified behavior to pull latest is fine, but I think there should be a mechanism to request a specific tag or commit. Usability boon if the tooling can check for updates and update `.rtx.toml` when requested.

If nothing else, this could aid reproducibility if everyone was locked to identical plugins.

**Comment by jdxcode** [comment]
> Unless I missed it, the .rtx.toml format lets you specify an external repository, and will always pull from HEAD.

No, that's not how it works at all. I explained how this works in a blog post I wrote this morning: https://jdxcode.com/posts/2023-04-08-10-rtx-features/

It only uses that field if the plugin doesn't exist.

**Comment by jdxcode** [comment]
that said, it isn't hard to add a sha here. This is already doable with `rtx plugins install`.

**Comment by dbready** [comment]
Appreciating that there is probably not a ton of churn in plugins or security risks, but something that came to my mind. Mostly because I was wondering who has the ability to influence a tool script on which I might rely. If I lean heavily into the rtx ecosystem and build up a development environment with a dozen different tools, that adds several potential vectors which are going to receive less scrutiny than the official release channels.

I never intend to use rtx in production, but one legitimate use case would be producing a Docker image. Ensuring there was repeatability in the versions of tooling that made it into an image.

**Comment by jdxcode** [comment]
I plan to move away from plugins generally and have the code that is now in bash scripts be in rust code instead. This is one of the reasons why.

Of course that means I'll need to take ownership of all the languages supported this way, but I think it's preferable. If you read [SECURITY.md](https://github.com/jdxcode/rtx/blob/main/SECURITY.md). I go into more detail on this.
