### ISSUE TITLE
Feature request: RTX_${PLUGIN}_VERSION for multiple versions

### ISSUE THREAD

**Issue by ericbn** [jdxcode/rtx#476]
Currently we can define multiple versions for a plugin, e.g. python, in the .rtx.toml file:
```toml
[tools]
python = ['3.11', '2.7']
```
or in the .tool-versions file:
```
python 3.11.3 2.7.18
```
but not using the `RTX_${PLUGIN}_VERSION` environment variable. At least the documentation only mentions how to use it to define one version for a plugin:
```
export RTX_PYTHON_VERSION=3.11
```

It would be nice to also be able to use `RTX_${PLUGIN}_VERSION` or some variation of it to define multiple versions for a plugin, like we can using the .rtx.toml or .tool-versions file.

**Comment by ericbn** [comment]
FYI [pyenv](https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-shell-advanced) uses `:` as separator:

```shell
$ pyenv shell 3.11 2.7
$ echo $PYENV_VERSION
3.11:2.7
```

**Comment by jdxcode** [comment]
I think I'm inclined towards any whitespace since that would work for #487 just as well. This is a bit of a strange feature because while rtx supports multiple versions with any language, to my knowledge it's only really ever used for python.

**Comment by ericbn** [comment]
Cool. I can also only think of multiple versions making sense for python, and specifically for python2 and python3.
