### ISSUE TITLE
PATH update behavior by rtx hooks

### ISSUE THREAD

**Issue by amoosbr** [jdxcode/rtx#48]
I created this as a separate issue, as this might be working as expected, be a more complex discussion, or a complicated change.
I look here especially at PATH, but it might be similar for other environment variables set by plugins.
For this example, I use `eval "$(rtx activate -s zsh)"` without direnv.

Issue: A manually customized PATH will be overwritten, when switching directories.
Expected: Only updated the PATH if necessary and in a "expected way".

Current behavior:

```sh
❯ echo $PATH
/Users/user/.local/share/rtx/installs/python/3.10.9/bin:...
❯ export PATH="$HOME/bin:${PATH}"
❯ echo $PATH
/Users/user/bin:/Users/user/.local/share/rtx/installs/python/3.10.9/bin:...

# switch to a directory not containing a local .tool-versions config
❯ cd dev

# expected: no change of PATH
# but customized PATH is overwritten and my custom added PATH value gone

❯ echo $PATH
/Users/user/.local/share/rtx/installs/python/3.10.9/bin:...
``` 

"Expected" behavior:
1. zsh load -> add global tool version bin paths to PATH
   1. on directory change, new directory has no local .tool-versions: instead of an overwrite (as is done today?), don't update/set PATH
      1. would fix a custom extended PATH being overwritten by rtx
   1. on directory change, new directory has local .tool-versions: "in place" update of rtx bin paths as needed according to local .tool-versions
      1. "in-place" update would allow keeping custom changes and order of PATH

I don't know, if this "expected" behavior is just my personal preference or expected by a majority of users. I can also not tell, if this is possible with rtx or if it would require using shims. Something you wanted to avoid with rtx.

For me, a valid alternative way forward, is probably to not use `eval "$(rtx activate -s zsh)"`, but direnv in combination with an initial global PATH setup via `eval "$(rtx env -s zsh)"`.

But wanted to mention this and open it for comments.

**Comment by jdxcode** [comment]
This is actually how direnv behaves. Any change to an environment variable after it is loaded will be wiped out if a new .envrc file is loaded that also changes `$PATH`:

```
bash-5.2$ echo $PATH
/Users/jdxcode/tmp/2:/Users/jdxcode/.bun/bin:*
bash-5.2$ export PATH="$HOME/test:$PATH"
bash-5.2$ echo $PATH
/Users/jdxcode/test:/Users/jdxcode/tmp/2:/Users/jdxcode/.bun/bin:*
bash-5.2$ cd ..
direnv: loading ~/.envrc
direnv: export ~PATH
bash-5.2$ echo $PATH
/Users/jdxcode/1:/Users/jdxcode/.bun/bin:*
```

**Comment by amoosbr** [comment]
You are correct, that the environment will be reset in direnv, if we change to a subdirectory with a new .envrc file.
This relates to the point 1**.ii** above, where instead of a 'in-place' update of PATH, it will be overwritten, when entering a directory containing a new .tool-versions file. Is also a valid strategy. The above mentioned was my personal 'nice to have' idea.

I think the more relevant use case is **1.i**. Where you go to a subdirectory **NOT** containing a new .envrc/.tool-versions file.
In this case in direnv, a customized PATH is still customized in the current shell and not overwritten on a directory change.

```sh
# rtx not activated in shell

❯ cd ~/dev/tmp/
❯ cat rtx-env-variables-direnv/.envrc
use rtx

❯ cat rtx-env-variables-direnv/.tool-versions
java temurin-11.0.15+10
golang 1.18.1
ruby 3.0.5

❯ echo $PATH
/Users/user/.local/share/rtx/installs/python/3.10.9/bin:...
❯ cd rtx-env-variables-direnv
direnv: loading ~/Projects/tmp/rtx-env-variables-direnv/.envrc
direnv: using rtx
direnv: export ~JAVA_HOME ~PATH ~RUBYLIB
❯ echo $PATH
/Users/user/.local/share/rtx/installs/python/3.10.9/bin:...
❯ export PATH="/customized/path:${PATH}"
❯ echo $PATH
/customized/path:/Users/user/.local/share/rtx/installs/python/3.10.9/bin:...

# switch to subdirectory NOT containing .envrc file
❯ cd test
❯ echo $PATH
/customized/path:/Users/user/.local/share/rtx/installs/python/3.10.9/bin:...
❯ cd ..
❯ echo $PATH
/customized/path:/Users/user/.local/share/rtx/installs/python/3.10.9/bin:...
```

Within rtx, the PATH is reset as soon as we switch the directory (see sample above).

As mentioned, this might just be my personal preference. And I think, for me it will work by not using `rtx activate` and instead `use rtx` in direnv for project related changes to the global settings.

**Comment by jdxcode** [comment]
ah ok, I missed that this is related to working in a subdirectory where the nearest parent with .tool-versions was unchanged.

I think my solution for having a direnv compatible PATH updating would actually resolve this as well. That change will make it so rtx _only_ modifies its own PATH entries and doesn't touch anything else that was modified. Right now it's a direnv-style that puts back the old PATH but we don't need to be that naive.

**Comment by amoosbr** [comment]
With `rtx 1.3.0` the use case **1.i.** is resolved.	I can now change to subdirectories, where the nearest parent with .tool-versions was unchanged, without my customized PATH being reset. 

I experienced another customized PATH related behavior, that I wanted to mention. As this wasn't relevant with `asdf` before, due to the shims, you can probably define what to expect in these scenarios.

```sh
# global rtx managed PATH - 👍
❯ cd ~/dev/tmp/
❯ echo $PATH
/Users/user/.local/share/rtx/installs/python/3.10.9/bin:...

# local rtx managed project PATH - 👍
❯ cd rtx-project
❯ cat .tool-versions
python 3.8.10
❯ echo $PATH
/Users/user/.local/share/rtx/installs/python/3.8.10/bin:...

# manually customized PATH - 👍
❯ export PATH="$HOME/bin:${PATH}"
❯ echo $PATH
/Users/user/bin:/Users/user/.local/share/rtx/installs/python/3.8.10/bin:...

# Case 1: switching to subdirectory with new .tool-versions file overwrites custom PATH changes.
# -> As you mentioned before and as direnv does, when not using source_up
❯ cd subproject
❯ cat .tool-versions
python 3.11.1
❯ echo $PATH
/Users/user/.local/share/rtx/installs/python/3.11.1/bin:...

# Case 2: switching back to the parent directory, will restore the previous PATH without custom changes
# -> This behavior differs from direnv
❯ cd ..
❯ echo $PATH
/Users/user/.local/share/rtx/installs/python/3.8.10/bin:...
```

With direnv, the previously used PATH is restored. As rtx is not direnv and custom modifications of the PATH are probably seldom. Especially, with additional subdirectory '.tool-versions' files involved.
Therefore I'd say, the desired `rtx-behavior` in this scenario is probably something you can verify with the community.

Should it be like direnv and overwrite changes or like asdf and not modifying a customized PATH or order at all. Of course, for asdf is was easy, as it didn't need to modify PATH.

As mentioned in my initial description **1.ii**, I would prefer an 'in-place' update by rtx to behave as asdf did. From the both cases in the code block above, `Case 2` would have a higher importance for me. It would be nice, if it would restore the PATH to the customized state seen before.

But keeping the current behavior isn't a blocker for me.

If you already have a `rtx-way` in mind, and it differs the current one, I can try to create a breaking e2e tests for it in the next days.

**Comment by jdxcode** [comment]
@amoosbr this should be resolved now as rtx now will only remove paths that it added for both direnv and non-direnv setups

**Comment by amoosbr** [comment]
@jdxcode Thanks, I can confirm, that I didn't see `rtx 1.5.1` removing any manually added PATH. Only thing, that might be an issue later in some use case might be, that the PATH order is modified. This would of course only be an issue, if I wanted to overwrite a binary also in one of the rtx provided tools.
As this is not a common work setting for me. Especially in combination with traversing to a new directory with a `.tool-versions` fie. We can see, if another user has a valid more common use case for keeping the PATH order (before rtx/after rtx)

```sh
❯ export PATH="$HOME/foo:${PATH}"
❯ echo $PATH
/Users/user/foo:/Users/user/.local/share/rtx/installs/python/3.8.10/bin:...
❯ cd subproject
rtx: python@3.11.1
❯ echo $PATH
/Users/user/.local/share/rtx/installs/python/3.11.1/bin:...:/Users/user/foo:...
❯ cd ..
rtx: python@3.8.10
❯ echo $PATH
/Users/user/.local/share/rtx/installs/python/3.8.10/bin:...:/Users/user/foo:...
```
