### ISSUE TITLE
Feature request: Support .ruby-version files

### ISSUE THREAD

**Issue by jordan-brough** [jdxcode/rtx#5]
You're probably already aware of this, but most of the ruby-versioning tools support a `.ruby-version` file, which just looks like this:
```
3.0.5
```

Would you please consider adding support for `.ruby-version` files?
It would make it easier for a Ruby dev to start using rtx immediately because many projects will already have a `.ruby-version` file.

Examples:
* [asdf](https://github.com/asdf-vm/asdf-ruby#ruby-version-file)
* [chruby](https://github.com/postmodern/chruby#default-ruby)
* [rbenv](https://github.com/rbenv/rbenv#how-it-works)
* [frum](https://github.com/TaKO8Ki/frum#features)
* [render.com](https://render.com/docs/ruby-version)

**Comment by jdxcode** [comment]
this works the same way as asdf, it's supported but you have to explicitly opt-in to enable [legacy version file](https://github.com/jdxcode/rtx#global-config-configrtxconfigtoml) support:

```sh-session
$ rtx plugin add ruby
$ mkdir -p ~/.config/rtx
$ echo 'legacy_version_file=true' >> ~/.config/rtx/config.toml
$ echo '3.1.3' > .ruby-version
$ rtx x -- ruby -v
v3.1.3
```

**Comment by jordan-brough** [comment]
Perfect!  I had just searched for `ruby-version` in the Readme and in the source code and hadn't seen it.

> perhaps I should create its own section and call out some common legacy file names.

👍 that would be great! Listing out common legacy file names would've helped me out.

**Comment by jdxcode** [comment]
I added this as part of https://github.com/jdxcode/rtx/pull/18

**Comment by jdxcode** [comment]
I'm going to change this to default to true while it's not terribly disruptive.
