### ISSUE TITLE
support installing all plugins with `rtx plugin add`

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#50]
`rtx plugin add` (with no arguments) should default to installing all of the active plugins

**Comment by codethief** [comment]
I just noticed your [comment on HN](https://news.ycombinator.com/item?id=34594304) and came to say that this is a fantastic change! Thank you!

**Comment by jdxcode** [comment]
technically I didn't implement this as described in the ticket, it's `rtx plugin add --all` but since you can also do `rtx install --all` I feel like that's probably going to be the more common command
