### ISSUE TITLE
Add --null option to rtx env to produce machine-parsable output

### ISSUE THREAD

**Issue by chrisbouchard** [jdxcode/rtx#508]
Currently, the only option we have to control the output from `rtx env` is the `--shell` flag, which controls which shell syntax is produced. Unfortunately, all of the shells supported have syntactic quirks that make using the result programmatically take extra work.

The system `env` command has a `--null` option (`-0` for short) that prints the environment with entries separated by ASCII NUL characters rather than newlines. Also, in general `env` does not include quotes around the values. These two features allow the output to be very easily parsed without requiring shell syntax parsing.

For example, with the environment

```sh
FOO='hello world'
BAR=123
```

`env -0` would output

```console
% env -0 | od -c
0000000   F   O   O   =   h   e   l   l   o       w   o   r   l   d  \0
0000020   B   A   R   =   1   2   3  \0
0000030
```

This is especially helpful because particular values can cause very difficult to parse as shell syntax. Consider an environment value like `FOO="\'"`, which would be printed by `rtx env` as something like

```
export FOO='\'\'''
```

## New Feature: `rtx env --null`

I would like to suggest that `rtx env` learn a `--null` option (and `-0` for short), and that `rtx env -0` produce output in the same format as `env -0`&mdash;that is, with no `export` keyword (or similar), with no quotes, and with ASCII NUL separators instead of newlines. These should probably conflict with the `--shell` option, since this output isn't meant to be read by any shell.

An alternative would be for `--shell` to learn a new value like `env`. For one thing, that feels slightly misleading, since the output isn't intended for any shell. Also, I feel like there's value in using the same flags as system `env` for discoverability.

## Inspiration

I'm investigating options for integrating rtx into a long-running multi-project emacs session, and one of the hurdles I've run into is how to get the environment from rtx into emacs. I think `rtx env` would tell me everything I need to know if I ran it from the buffer's directory, but then I have to deal with parsing the output.

I could alternative use `rtx exec -- env -0`, but that dumps the entire environment, not just the values rtx wants to set&mdash;not the end of the world, but it feels wasteful since emacs already knows most of it. I could maybe get around that by using `env -i rtx exec -- env -0` to run rtx in an empty envirnoment so there _are_ no other values to print. That doesn't currently work (#507), but even if it did it would at least require merging the `PATH` it prints into the `PATH` in emacs, and possibly other tool-specific values as well. Also also, the user may have `RTX_` flags set that need to be available.

On the whole, using `rtx env` feels like the right solution, if it could produce a machine-parsable format.

**Comment by jdxcode** [comment]
I'm more inclined to support json over having things be null-delimited. Otherwise I'd eventually have to deal with escaping nulls and end up with a custom format. It's also more human-readable.

**Comment by chrisbouchard** [comment]
Whoah, ok. Sad there wasn't any discussion of pros and cons, but I'll see what I can do with JSON in emacs.

**Comment by chrisbouchard** [comment]
And for what it's worth, I'm not sure I understand what you mean by

> Otherwise I'd eventually have to deal with escaping nulls and end up with a custom format.

The format produced by `env -0` is a safe format, no escaping required. Environment variable names are not permitted to contain `=`, and their values are considered to end at the first NUL character. This is true [in POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/)) and [in Windows](https://learn.microsoft.com/en-us/windows/win32/procthread/environment-variables).

**Comment by jdxcode** [comment]
oh ok I somehow thought you could put null values into a variable—thanks for correcting me on that point. I know it's common to use null with `find -print0 | xargs -0`, but I haven't come across it very often in other CLI use-cases. I am more familiar with using json or just making sure output is easy to parse with awk rather than using nulls.

I would prefer by default using json in rtx for machine-readable output since it can be used to represent structure in a way that null delimitation couldn't. That doesn't apply to `rtx env` though. I think `rtx env --json` makes sense to have regardless of your use-case. If you find json is hard to work with for your emacs use-case I can look into adding null delimitation as well.
