### ISSUE TITLE
Make it easy to copy binaries installed by rtx to somewhere else

### ISSUE THREAD

**Issue by sschuberth** [jdxcode/rtx#512]
I'm playing with rtx in a Dockerfile to build an image with custom versions of various tools. However, as building some of the tools (like Python) requires compilers etc. that are not needed at runtime of the tools, it would make sense to create a multi-stage Dockerfile with one image to build the tools, and another (slimmer) one to run the tools. That'd require to copy over the built binaries of the tools from the "build time" image to the "runtime" image.

I guess a convenient way to achieve this would be an rtx command than could tar up a specific tool, so I could untar it on any machine (with the same os / arch) that also has rtx installed, and then use rtx as if it was used to install the tool on that machine initially.

**Comment by jdxcode** [comment]
I'm not sure I follow, would copying `~/.local/share/rtx/installs` get you what you're looking for? I'm not sure a command is necessary for that.
