### ISSUE TITLE
CLI commands to manage env vars

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#517]
There should be some CLI commands to manage arbitrary env vars. Not really sure what they should be since `rtx env` is already used for something else.

`rtx set-env` is one idea I had. Or maybe env-set which will sort better.

**Comment by smbl64** [comment]
Is this idea something similar to what `direnv` does?

**Comment by jdxcode** [comment]
direnv doesn't have this feature

**Comment by smbl64** [comment]
I find `rtx` very useful, so I would like to contribute 😀 

To understand the feature, how is this different from using `export FOO=bar` in current shell?
Or in case of `direnv`, one can write `export FOO=bar` in their `.envrc` and it will get activated once user enters that folder.

**Comment by smbl64** [comment]
Clear! 
You can assign this ticket to me. It might take a bit longer as I need to learn the codebase first :)

**Comment by smbl64** [comment]
I am trying to read `.rtx.toml` file in current directory like this:
```rust
fn get_rtx_toml() -> Result<RtxToml> {
    let path = dirs::CURRENT.join(RTX_DEFAULT_CONFIG_FILENAME.as_str());
    let rtx_toml = if path.exists() {
        RtxToml::from_file(&path, false)? // TODO: truested or not?
    } else {
        RtxToml::init(&path, true)
    };

    Ok(rtx_toml)
}
```

While reading an existing TOML file, where can I see if it is already trusted?

**Comment by smbl64** [comment]
Regarding the command (`set-env`), I think we should create a subcommand under `env`, like this:

```
rtx env set FOO=bar
```

This way we can add more subcommands there in the future (`remove`, `ls` etc..)

This is somehow similar to `rtx alias` and its subcommands.

What do you think?

**Comment by jdxcode** [comment]
not sure about the trusted stuff right now, if you can get a PR ready I'll review it and let you know what I think we should do. We may want to refactor the trusted stuff a little bit but I don't know if that makes sense here or not.

I mentioned the subcommand thing in the issue description here. I think because `rtx env` is a completely different command that really doesn't have anything to do with the behavior of this new command it doesn't make sense to put it there. I don't think it would be discoverable. If `rtx env` did not already exist, it would make sense to make `rtx env` list all of the current env vars in the toml file and `rtx env set` would modify them.

This is why I was thinking `set-env` or maybe `env-set` which would sort better, but on the other hand I think having a set of CRUD commands like we have for `rtx alias` and `rtx settings` is probably the right thing to do.

We just can't use `rtx env` since that's taken and definitely can't be changed at this point. Some ideas to get the ball rolling on this:

* `rtx local-env set`
* `rtx env-vars set`
* `rtx toml-env set`
* `rtx cwd-env set`

I don't love any one of these, but I'll think more about it and see if we can come up with a good idea.

**Comment by jdxcode** [comment]
my memory is a bit hazy but I think this is the only section where I read the toml file outside of the complex toolset parsing that isn't likely helpful for you:

https://github.com/jdxcode/rtx/blob/main/src/cli/local.rs#L105-L109C7

However that uses the generic "config_file" interface which could be a legacy file (.node-version) or .tool-version file—neither of which is relevant to you since env vars I believe are only ever used in .rtx.toml files.

One thing we're going to have to watch out for is a situation where you have a `.rtx.local.toml` file and you run `rtx env-vars set FOO=bar`. If that local file already defines something for FOO it would probably write to `.rtx.toml` and not `.rtx.local.toml` and not actually change anything. For v1 we can probably just not worry about this use-case or maybe show a warning if the variable is overridden but something to think about for the future.

**Comment by smbl64** [comment]
Sorry for the long pause in replying. Got really busy with some personal stuff 😅 

I just opened a draft PR regarding this issue.

Reading your comments, I think I like `env-vars` more than `env-file`. The reason being that the TOML file is not just for env variables. Calling it `env-file` might give the impression that it is used for env variables only?

Summarizing your comments, this is what comes to my mind:
```
$ rtx env-vars FOO=bar # modifies .rtx.toml
$ rtx env-vars --rm FOO # removes FOO from .rtx.toml

$ rtx env-vars .rtx.dev.toml FOO=bar
$ rtx env-vars .rtx.dev.toml --rm FOO # removes FOO from .rtx.dev.toml
```

`rtx env-vars [TOML FILE] [OPTIONS] ARGS...`

**Comment by jdxcode** [comment]
Let’s make the file an option, e.g.: `--file`. That’ll make it a lot easier to implement and more clear to the user.
