### ISSUE TITLE
cargo-binstall type error

### ISSUE THREAD

**Issue by eugenesvk** [jdxcode/rtx#52]
Thanks for the tip about `cargo-binstall`, seems like a great alternative to wasting all the time rebuilding everything from scratch!

However, I couldn't use it with your project. After manually downloading the prebuilt cargo-binstall binary and simply cloning your project, then trying to run `cargo binstall rtx-cli` from your project's root on a macOS I get the following error:

```sh
cargo binstall rtx-cli
 INFO resolve: Resolving package: 'rtx-cli'
ERROR Fatal error:

  × For crate rtx-cli: invalid type: string "rtx/bin/rtx", expected struct PkgOverride for key `package.metadata.binstall.overrides.bin-dir` at line 49
  │ column 11
  ├─▶ invalid type: string "rtx/bin/rtx", expected struct PkgOverride for key `package.metadata.binstall.overrides.bin-dir` at line 49 column 11
  ╰─▶ invalid type: string "rtx/bin/rtx", expected struct PkgOverride for key `package.metadata.binstall.overrides.bin-dir` at line 49 column 11
```

I see that your Cargo.toml has
```toml
[package.metadata.binstall.overrides]
bin-dir = "rtx/bin/rtx"
```
(though it's not on line 49, but maybe the crate.io version is different?)
Tried changing it, but it has no effect (likely for the same reason)

**Comment by jdxcode** [comment]
hrm, this was working at one point but I probably changed something and broke it. I'll figure out what's going on here.

**Comment by jdxcode** [comment]
You should be good now:

```
~ ❯ cargo binstall rtx-cli
 INFO resolve: Resolving package: 'rtx-cli'
 WARN The package rtx-cli v1.2.7 will be downloaded from github.com
 INFO This will install the following binaries:
 INFO   - rtx (rtx -> /Users/jdxcode/.cargo/bin/rtx-v1.2.7)
 INFO And create (or update) the following symlinks:
 INFO   - rtx (/Users/jdxcode/.cargo/bin/rtx -> rtx-v1.2.7)
Do you wish to continue? yes/[no]
? yes
 INFO Installing binaries...
 INFO Done in 5.959202917s
```
