### ISSUE TITLE
Improve installation instruction structure

### ISSUE THREAD

**Issue by tenjaa** [jdxcode/rtx#549]
Hi,

I am using rtx on a Mac and therefore used brew to install it.
Then it did not work and I had a look at the quickstart.
There I found the activate command
```
echo 'eval "$(~/bin/rtx activate zsh)"' >> ~/.zshrc
```
But this one does not work when using brew with the following error:
```
/Users/<user>/.zshrc:104: no such file or directory: /Users/<user>/bin/rtx
```

All the documentation is present but it is a bit confusing for new users (or just me?).
The main issue to me is, that the (homebrew) instructions are separated from the `activate` command.

How do you feel about a different readme structure? This is how I would do it
- ...
- About
- Install
  1. Install binary
     - homebrew
     - cargo
     - npm
     - ...
  2. Register shell hook
     - bash
     - zsh
     - fish
     - ...
- Uninstall
- ...

**Comment by jdxcode** [comment]
I don't understand, this is the current structure

<img width="230" alt="Screenshot 2023-05-19 at 07 10 51" src="https://github.com/jdxcode/rtx/assets/216188/2cebe95c-2285-41f4-b129-b012cc68c3e3">

**Comment by jdxcode** [comment]
there is also the [beginner's guide](https://dev.to/jdxcode/beginners-guide-to-rtx-ac4)

**Comment by tenjaa** [comment]
I try to elaborate a bit more but this is purely opinion based. If you disagree feel free to close it.

I am coming from asdf and as a colleague recommended it I never really thought about how it works.
In their installation instructions it says "Run `brew install` and when using ohmyzsh add the plugin, otherwise add this command to your .zshrc".
Now I stumbled upon rtx and just ran what it says in the installation instructions: `brew install`.

For me it is not obvious that there are basically two parts of the installation. 1. Download the binary and 2. add the shell hook.

In my opinion my proposal makes this a bit more obvious, that there are two required steps. But as I said in the beginning, this is mainly opinion based.

**Comment by jdxcode** [comment]
I know asdf has a bunch of combinations like ["PowerShell Core & Homebrew"](https://asdf-vm.com/guide/getting-started.html#_3-install-asdf), but IMO that's just a lot of noise. I think 2 separate sections is fine even if the reader needs to fill in some of the gaps themselves.

**Comment by tenjaa** [comment]
I think now we are talking about the same thing!

Here is a small PR how I would think the installation instructions are more obvious:
https://github.com/jdxcode/rtx/pull/558
