### ISSUE TITLE
`node` and `nodejs` commands show up in help but don't exist

### ISSUE THREAD

**Issue by Xenfo** [jdxcode/rtx#551]
![image](https://github.com/jdxcode/rtx/assets/46873232/ccf987e6-1441-4411-99f7-b3f68072a1fb)
![image](https://github.com/jdxcode/rtx/assets/46873232/0f364089-3e78-4b8a-8515-32879ad53870)

**Comment by jdxcode** [comment]
there aren't actually commands there, but I have a PR that will make this more clear
