### ISSUE TITLE
Support `.elixir-version` and `.erlang-version` for "legacy" files

### ISSUE THREAD

**Issue by halostatue** [jdxcode/rtx#58]
I have added functionality to my `direnv` configuration for [Erlang](https://github.com/direnv/direnv/wiki/Erlang#automated-fuzzy-erlang-version-switching) and [Elixir](https://github.com/direnv/direnv/wiki/Elixir#automated-fuzzy-elixir-version-switching) which provide direnv-based support for `.erlang-version` and `.elixir-version`, and I’ve never used exenv (which is archived in any case).

**Comment by halostatue** [comment]
I see. I’m not familiar with how ASDF works because I have refused to use it because of its use of shims.

**Comment by jdxcode** [comment]
> I see. I’m not familiar with how ASDF works because I have refused to use it because of its use of shims.

:)

I was hesitant to add the legacy filenames to the readme for exactly this reason, I felt like it would give this impression. Maybe I could add a note to that part of the readme explaining this.
