### ISSUE TITLE
Alpine releases are failing

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#593]
the github action that builds alpine releases has quit functioning: https://github.com/jdxcode/rtx/actions/runs/5141174991/jobs/9253686633

here is the error:

```
>>> rtx: Updating the sha512sums in /home/packager/aports/community/rtx/APKBUILD...
+ cat /github/home/.abuild/abuild.conf
PACKAGER_PRIVKEY="/github/home/.abuild/-640e56d3.rsa"
+ abuild -r
>>> rtx: Building community/rtx 1.30.5-r1 (using abuild 3.11.0-r1) started Thu, 01 Jun 2023 07:05:10 +0000
>>> rtx: Checking sanity of /home/packager/aports/community/rtx/APKBUILD...
>>> rtx: Analyzing dependencies...
ERROR: unable to select packages:
  .makedepends-rtx-20230601.070511:
    masked in: cache
    satisfies: world[.makedepends-rtx=20230601.070511]
  cargo-auditable (no such package):
    required by: .makedepends-rtx-20230601.070511[cargo-auditable]
>>> ERROR: rtx: builddeps failed
>>> rtx: Uninstalling dependencies...
ERROR: No such package: .makedepends-rtx
Error: Process completed with exit code 1.
```

unfortunately I have no idea what that means yet

**Comment by setsarentdoors** [comment]
Seems related to the migration to `cargo-auditable`: https://gitlab.alpinelinux.org/alpine/aports/-/blob/552fe4d04b7029fcc832da741ba94bd01c15a1b8/community/rtx/APKBUILD

`cargo-auditable` isn't available for v3.18 and below but is available on edge branch: https://pkgs.alpinelinux.org/packages?name=cargo-auditable&branch=edge&repo=&arch=&maintainer=

I'm able to build this release locally after reverting the changes to `APKBUILD`
