### ISSUE TITLE
Include autocompletion and man pages in nix build

### ISSUE THREAD

**Issue by szaffarano** [jdxcode/rtx#602]
Neither man pages nor auto-completion files are included when installing `rtx` using Nix.

**Comment by szaffarano** [comment]
Closing based on [this comment](https://github.com/jdxcode/rtx/pull/601#issuecomment-1578812117).

Do you think it is worth mentioning the nix pkgs approach in the install instructions?

**Comment by jdxcode** [comment]
I assume so. I'm not the best to draft it since I'm not a nix user though. If you or maybe @konradmalik want to send over a PR to replace the instructions with nixpkgs I would definitely accept it
