### ISSUE TITLE
Question: How can I disable [WARN] Tool not installed (for python)

### ISSUE THREAD

**Issue by vihu** [jdxcode/rtx#618]
Hello,

Thank you for this excellent alternative to asdf!

I tried looking around for this and changing the relevant env vars to `INFO` but I still get this behavior:

```shell
❯ cd personal/rough
[WARN] Tool not installed: python@3.11.3

~/personal/rough
.venv ❯ cat .python-version
3.11.3

~/personal/rough
.venv ❯ cd -
~
```

I am using pyenv to manage python versions. The `.venv` is created like so: `python3 -m venv .venv`. Its just a minor annoyance that I get the `[WARN] Tool not installed ..` message. Can someone please tell me how to curb this message? Thanks!

**Comment by jdxcode** [comment]
> I am using pyenv to manage python versions.

huh? what is the contents of your `.rtx.toml`?

**Comment by vihu** [comment]
> > I am using pyenv to manage python versions.
> 
> huh? what is the contents of your `.rtx.toml`?

So here's the global config:

```shell

❯ bat .config/rtx/config.toml
[tools]
nodejs = "lts"
erlang = "24"

❯ rtx list
erlang 24.3.4.12       ~/.config/rtx/config.toml 24
nodejs 18.16.0 (outdated) ~/.config/rtx/config.toml lts

❯ pyenv versions
  system
  3.10.6
* 3.11.3 (set by ~/.pyenv/version)
```

I don't have any project specific `.rtx.toml` (if that's what you were asking).

**Comment by jdxcode** [comment]
oh I see what you're saying. You use rtx for erlang and node but not python, however you have a `.python-versions` file and rtx is picking that up. You should be able to use `rtx settings set legacy_version_file false` (notably this appears absent from the docs), however that will disable all legacy version files.

What needs to happen is there needs to be a way to disable certain core plugins I think. Or just disable legacy_version_file support for particular plugins. This is a gap currently.
