### ISSUE TITLE
replace nix instructions with nixpkgs

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#635]
See https://github.com/NixOS/nixpkgs/pull/218450. The nix instructions in the README should be replaced with this. However I'm not a nix user so I will definitely need someone else to help rewrite that section.

_Originally posted by @jdxcode in https://github.com/jdxcode/rtx/issues/601#issuecomment-1578812117_

**Comment by hiljusti** [comment]
I recommend waiting until it's included in at least one Nix release. The next release would be 23.11 (i.e. this coming November)

I started a workflow to get the initial commit backported for 23.05: https://github.com/NixOS/nixpkgs/pull/241594
