### ISSUE TITLE
Ruby plugin adds file that attempts to reshim - Error if asdf is not installed

### ISSUE THREAD

**Issue by wmbest2** [jdxcode/rtx#64]
The Ruby plugin tries to reshim on each gem install. 

https://github.com/asdf-vm/asdf-ruby/blob/master/rubygems-plugin/rubygems_plugin.rb

Leading to this error:
```
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - asdf
        ~/.local/share/rtx/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:15:in ``'
        ~/.local/share/rtx/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:15:in `block (2 levels) in <top (required)>'
        ~/.local/share/rtx/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:14:in `each'
        ~/.local/share/rtx/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:14:in `block in <top (required)>'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/installer.rb:381:in `block in run_post_install_hooks'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/installer.rb:380:in `each'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/installer.rb:380:in `run_post_install_hooks'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/installer.rb:345:in `install'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/resolver/specification.rb:104:in `install'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:194:in `block in install'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:182:in `each'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:182:in `install'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:214:in `install_gem'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:230:in `block in install_gems'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `each'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `install_gems'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:169:in `execute'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/command.rb:323:in `invoke_with_build_args'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/command_manager.rb:185:in `process_args'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/command_manager.rb:149:in `run'
        ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/gem_runner.rb:51:in `run'
```

I "fixed" the problem by deleting the `rubygems_plugin.rb` file entirely. But I'm curious if it'd be possible to have an alias for `asdf` that no-ops these functions.

Apologies if this is a duplicate, I looked around and didn't see anything related exactly to this.

**Comment by jdxcode** [comment]
Is that what `RUBYLIB` does? I was wondering. I think we should remove that since we don't use shims.

On Tue, Jan 31, 2023, at 11:47, Bill Best wrote:
> 
> 
> The Ruby plugin tries to reshim on each gem install.
> 
> https://github.com/asdf-vm/asdf-ruby/blob/master/rubygems-plugin/rubygems_plugin.rb
> 
> Leading to this error:
> 
> `ERROR:  While executing gem ... (Errno::ENOENT)
>     No such file or directory - asdf
>         ~/.local/share/rtx/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:15:in ``'
>         ~/.local/share/rtx/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:15:in `block (2 levels) in <top (required)>'
>         ~/.local/share/rtx/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:14:in `each'
>         ~/.local/share/rtx/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:14:in `block in <top (required)>'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/installer.rb:381:in `block in run_post_install_hooks'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/installer.rb:380:in `each'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/installer.rb:380:in `run_post_install_hooks'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/installer.rb:345:in `install'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/resolver/specification.rb:104:in `install'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:194:in `block in install'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:182:in `each'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:182:in `install'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:214:in `install_gem'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:230:in `block in install_gems'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `each'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `install_gems'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:169:in `execute'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/command.rb:323:in `invoke_with_build_args'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/command_manager.rb:185:in `process_args'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/command_manager.rb:149:in `run'
>         ~/.local/share/rtx/installs/ruby/3.2.0/lib/ruby/3.2.0/rubygems/gem_runner.rb:51:in `run'
`

**Comment by jdxcode** [comment]
yeah this seems to fix it:

```
RUBYLIB= gem install neovim
```

I think I'm just going to blacklist this env var entirely for now.

**Comment by wmbest2** [comment]
yep! That would do it too, was unsure how you were handling these special cases. Thanks

**Comment by jdxcode** [comment]
This is a bad bug so I'm pushing out 1.2.8 with a fix right away. Funny enough I just _fixed_ this environment variable in the last release but it turns out we _don't_ want this env var after all!
