### ISSUE TITLE
Add install command to "Tool not installed" warning

### ISSUE THREAD

**Issue by pzcfg** [jdxcode/rtx#649]
Very minor / nice to have, but it would be nice if the "Tool not installed" warning (e.g. `[WARN] rtx::toolset: Tool not installed: nodejs@16.16.0`) also included the command to install it, like `[WARN] rtx::toolset: Tool not installed: nodejs@16.16.0 (To install: rtx install nodejs@16.16.0)`

**Comment by jdxcode** [comment]
I could add this but the easy way is just running `rtx i` since that installs all missing versions.
