### ISSUE TITLE
set environment variable when cd into project without direnv

### ISSUE THREAD

**Issue by dfang** [jdxcode/rtx#670]
say I have go 1.20 installed global, 1.18 in project. when I cd into project directory. how to run `export GOROOT="$(rtx where golang)/go/" automatically.

for now, I have to run this manually, maybe it's possible to use direnv, but I prefer not.

```
.rtx.toml in project root

[env]
# supports arbitrary env vars so rtx can be used like direnv/dotenv
GOPROXY="https://mirrors.tencent.com/go/"
RTX_GOLANG_SKIP_CHECKSUM=true
RTX_GOLANG_DOWNLOAD_MIRROR="https://mirrors.aliyun.com/golang/"
GOROOT="$(rtx where golang)/go/"

[tools]
golang = '1.18'

[plugins]
# specify a custom repo url
# note this will only be used if the plugin does not already exist
golang = 'https://github.com/rtx-plugins/rtx-golang'

[settings] # project-local settings
verbose = true
```

when I cd into the project root, `go env GOROOT` returns go: cannot find GOROOT directory: $(rtx where golang)/go

https://github.com/jdxcode/rtx#environment-variables-in-rtx

**Comment by jdxcode** [comment]
you should try the core plugin since the bash plugin you're using I won't be contributing to anymore. Just enable experimental mode and uninstall it.

You shouldn't need to do this though, rtx sets that env var automatically:

https://github.com/jdxcode/rtx/blob/7144a277f323310f36f42225064718580b7f180a/src/plugins/core/go.rs#L182-L197

**Comment by dfang** [comment]
```
λ ls ~/.local/share/rtx/plugins/
go

λ ls ~/.local/share/rtx/plugins/go/
LICENSE  README.md  bin  lib  set-env.fish  set-env.zsh  spec  test-fixtures

λ cd !$
cd ~/.local/share/rtx/plugins/go/

λ git remote -v
origin	https://github.com/rtx-plugins/rtx-golang.git (fetch)
origin	https://github.com/rtx-plugins/rtx-golang.git (push)
```

I'm using official plugin, after removed asdf and direnv related stuff completely, I got what I what.

it seems not necessary to enable experimental mode.

thanks !!!
