### ISSUE TITLE
use positional arg for `rtx activate SHELL`

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#71]
I regret using an option for `rtx activate`, `rtx hook-env`, and `rtx env`. This is how you use them currently:

```
$ rtx activate -s bash
$ rtx hook-env -s bash
$ rtx env -s bash
```

this is how they should work:

```
$ rtx activate bash
$ rtx hook-env bash
$ rtx env -s bash
```

In order to not break current users we should make either usage supported but `-s` should have `hide = true` set in the clap config so it doesn't show in the help.

We're not doing `rtx env` because it also accepts runtimes as positional arguments and this is an optional argument.

**Comment by delicb** [comment]
I guess this issue can be closed now since #85 was merged.
