### ISSUE TITLE
Issue with Node pre-commit hooks in IDE etc.

### ISSUE THREAD

**Issue by AlecRust** [jdxcode/rtx#726]
I have a pretty typical Husky setup in a project, where `lint-staged` is called in a pre-commit hook:

`.husky/pre-commit`:
```sh
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
```

If I commit via the GUI Git client [Sourcetree](https://www.sourcetreeapp.com/) (and I assume other clients/IDE environments) my `~/.zshrc` is not loaded in the basic shell environment.

To work around this as-per [Husky docs](https://typicode.github.io/husky/troubleshooting.html#command-not-found) I have a `~/.huskyrc` file which runs before the commit hooks for loading extra commands.

With asdf, this contents of `~/.huskyrc` worked to load the `npx` shim:

```sh
# Add asdf shims to PATH
export PATH="$HOME/.asdf/shims:$PATH"
```

However with rtx, this contents of `~/.huskyrc` does **not** work to load the `npx` shim:

```sh
# Add rtx shims to PATH
export PATH="$HOME/.local/share/rtx/shims:$PATH"
```

It looks like `npm` shim is loaded, but not the `npx` shim I need. Why is this behaviour different from asdf?

I've also tried `rtx activate` but I see in your documentation you recommend shims for this case.

**Comment by jdxcode** [comment]
yeah I'm missing the shim as well. Notably `npx` and `corepack` are symlinks so that's probably the issue. Looking further...

**Comment by jdxcode** [comment]
This was a bug introduced in https://github.com/jdxcode/rtx/pull/672
