### ISSUE TITLE
load when running command in ssh

### ISSUE THREAD

**Issue by mustafa0x** [jdxcode/rtx#746]
```bash
$> ssh $HOST 'node --version'
bash: line 1: node: command not found
```

I also tried `ssh $HOST 'eval "$(rtx activate bash)" && node --version'` but that gave the same error.

**Comment by jdxcode** [comment]
as described in the docs, you should use shims for non-interactive setups

**Comment by mustafa0x** [comment]
Thanks Jeff, I searched issues, but missed the docs!

**Comment by jdxcode** [comment]
for an explanation: `rtx activate` updates PATH when the prompt is displayed. Since the prompt never gets displayed in non-interactive prompts it isn't possible for it to function.

**Comment by mustafa0x** [comment]
> for an explanation: `rtx activate` updates PATH when the prompt is displayed. Since the prompt never gets displayed in non-interactive prompts it isn't possible for it to function.

Maybe if non-interactive, `rtx activate` adds `~/.local/share/rtx/shims` to `$PATH`?

Does that make sense? Or too risky?
