### ISSUE TITLE
Unable to install python in wsl

### ISSUE THREAD

**Issue by Random-Nobody** [jdxcode/rtx#770]
**Describe the bug**
Python fails to install on wsl.
As best as I can tell, problem is
`Traceback (most recent call last):
  File "<frozen zipimport>", line 576, in _get_decompress_func
ModuleNotFoundError: No module named 'zlib'`
which is confusing because ofc it's not there; python's not installed yet

**To Reproduce**
run
`rtx install python@latest`
on wsl Ubuntu 22.04.3 LTS

**Expected behavior**
python hopefully installing without problem

**`rtx doctor` output**

```
rtx version:
  1.35.8 linux-x64 (3d305dc 2023-08-01)

build:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL, SELF_UPDATE
  Built: Tue, 01 Aug 2023 19:00:53 +0000
  Rust Version: rustc 1.71.0 (8ede3aae2 2023-07-12)
  Profile: release

shell:
  /usr/bin/zsh
  zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

rtx data directory:
  /home/huang/.local/share/rtx

rtx environment variables:
  RTX_SHELL=zsh

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "trusted_config_paths": "[]", "verbose": "false"}

config files:
  /home/huang/.config/rtx/config.toml

plugins:
  go       (core)
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)

toolset:
  node@latest, go@latest

No problems found
```

**Additional context**
prior to this, `rtx install python@latest` was failing due to not having a c compiler or something, so I ran `apt install build-essentials gdb`

**Comment by jdxcode** [comment]
try `sudo apt install zlib1g zlib1g-dev libssl-dev libbz2-dev libsqlite3-dev`

also see https://github.com/pyenv/pyenv/wiki/Common-build-problems#build-failed-error-the-python-zlib-extension-was-not-compiled-missing-the-zlib

and https://github.com/pyenv/pyenv/wiki#suggested-build-environment

**Comment by Random-Nobody** [comment]
off ok. That's my mistake. Haven't had a new machine in a while; did not occur to me that I'd still need dependencies.
