### ISSUE TITLE
Show where tool versions are defined when calling `rtx current`

### ISSUE THREAD

**Issue by jsfr** [jdxcode/rtx#784]
When calling `asdf current`, part of the information displayed is where each tool version is defined. This is super helpful to understand what has been used to source the environment you're currently in.

For `rtx current`, however, only the tool versions are currently displayed.

It would be nice if `rtx` could show where tool versions are sourced from, similarly to how `asdf` does it.

Example output from `asdf current`

```text
❯ asdf current
bun             0.7.3           Not installed. Run "asdf install bun 0.7.3"
golang           system         /Users/jens/.tool-versions
just               system       /Users/jens/.tool-versions
kubectl         1.22.17         /Users/jens/.tool-versions
nodejs          20.5.0          /Users/jens/Repos/my-repo/.tool-versions
pnpm            8.6.12          Not installed. Run "asdf install pnpm 8.6.12"
poetry           1.5.1          /Users/jens/.tool-versions
yarn               1.22.19      /Users/jens/.tool-versions
zigmod           r86            /Users/jens/.tool-versions
```

**Comment by jdxcode** [comment]
Just use `rtx ls`

**Comment by jsfr** [comment]
Look at that! I wasn't aware of this, but that 100% solves what I'm asking. I'll close this ticket, thank you for the swift response.
