### ISSUE TITLE
Add `~/.default-cargo-crates` configuration support

### ISSUE THREAD

**Issue by mehalter** [jdxcode/rtx#788]
I've been really loving `rtx` and specifically the ability to configure default package files such as `RTX_PYTHON_DEFAULT_PACKAGES_FILE` and `RTX_NPM_DEFAULT_PACKAGES_FILE` to put configuration files in the same location not in my home directory. `asdf-rust` also has a similar feature to put a `~/.default-cargo-crates` file (https://github.com/code-lever/asdf-rust/issues/20). It would be awesome to have a similar environment variable so I can put default cargo packages in the same location (maybe `RTX_CARGO_DEFAULT_CRATES`).

Thanks for all your hard work on this project!

**Comment by jdxcode** [comment]
I don't understand, aren't you using asdf-rust in rtx?

**Comment by mehalter** [comment]
I am, and it works great and I can make the file `~/.default-cargo-crates` and it works perfectly. I noticed that rtx adds environment variables for node and python for changing the location because `asdf-python` and `asdf-node` also only look at `~/.default-python-packages` and `~/.default-npm-packages` respectively. They don't have any knowledge of the `RTX_PYTHON_DEFAULT_PACKAGES_FILE` and `RTX_NPM_DEFAULT_PACKAGES_FILE` environment variables. I think it would be nice to have a uniform support with the `asdf-rust` as well to specify `RTX_CARGO_DEFAULT_CRATES` to change the location of that file in a similar manner.

**Comment by mehalter** [comment]
Thanks for the information! I didn't realize that `python` and `node` were reimplemented here as core plugins. I thought this was adding shims into the `asdf-plugins`. Sorry for the noise!

**Comment by farzadmf** [comment]
@mehalter Is there any documentation of using `asdf-rust` in mise? I really like the auto-install of packages feature, but I can't make it work by doing `mise use -g rust`

**Comment by mehalter** [comment]
It looks like as of last week `rust` is a core plugin (https://github.com/jdx/mise/pull/3219). It looks like this new plugin doesn't support default crates yet. @jdx could this issue get reopened if this feature is planned similarly to how it's implemented in the core `python` and `node` plugins?

**Comment by farzadmf** [comment]
@jdx I think it's mostly a matter of convenience TBH. Would be nice to have a consistent experience between all the tools and not having to consider Rust as an exception compared to Python and Node.

I do understand the core and non-core plugins, but I personally think it would be nice to achieve things in the tools in a similar manner.

And also, not sure if the `cargo` backend is suitable for the use case or not, but a couple of crates I'm using are not "global binaries" if I'm not mistaken: [cargo-update](https://github.com/nabijaczleweli/cargo-update), and [cargo-generate](https://github.com/cargo-generate/cargo-generate)

Or ... maybe I _am_ mistaken and they _do_ install global binaries `cargo-install-update` and `cargo-generate` 🤔 

But anyways, as I mentioned, it'd be nice to be able to just do `mise use -g rust` and crates are installed as well 🙂

**Comment by jdx** [comment]
I don't think cargo has any sort of "non-global" binaries. It has components but those aren't installable via crates either. I don't see why you would need or want to have cargo automatically compile binaries when installing a new version. All `cargo install` does is give you a global binary in `~/.cargo/bin` which is the same functionality that the cargo backend provides.

**Comment by farzadmf** [comment]
Makes sense @jdx ; thanks for the explanation

In case you didn't see my question in https://github.com/jdx/mise/pull/2701#issuecomment-2512294350: does `mise use -g cargo:<crate>` also take care of updating the crate?

**Comment by jdx** [comment]
not unless you specify `@latest` but you really probably want to use `mise up` for upgrading anyways
