### ISSUE TITLE
add security warnings when installing plugins

### ISSUE THREAD

**Issue by jsifuentes** [jdxcode/rtx#790]
When installing a runtime from a plugin that you don't have installed yet, there should be a security warning about the risk of installing community-created plugins.

There's only so much that can be done to prevent a supplychain attack with the current asdf ecosystem, but I think education is important and the risks should be laid out up-front when installing a plugin.

--

When using `rtx plugins ls-remote 1password-cli`, I receive a dialog:

> Plugin 1password-cli is not installed, would you like to install it?

This message does not contain information on where the plugin is about to be pulled from if I say yes.

Likewise, when using `rtx install 1password-cli@latest`, the plugin installation happens automatically with no dialog asking for approval. This is a bit unexpected given the behavior when using `plugins ls-remote`.

When a plugin needs to be installed, unless I provide `--no-interaction` or something similar, I'd like see a warning similar to:

> Plugin 1password-cli is not installed.
>
> **This plugin will be installed from: hxxps://github.com/username/asdf-1password-cli#commit**
>
> :warning: This plugin is community-maintained. Community-maintained plugins are not actively monitored for security issues and are not verified for integrity. You should always review the contents of a plugin before continuing with the installation.
>
> Do you want to install this plugin? [yes/no] 

This would provide an easier way for users to copy/paste the GitHub link and review the plugin before installation.

**Comment by jdxcode** [comment]
> This message does not contain information on where the plugin is about to be pulled from if I say yes.

I'd be happy with adding the repo URL to this, that's not a hard change I don't think—however I don't think this dialog is especially common.

> When a plugin needs to be installed, unless I provide --no-interaction or something similar, I'd like see a warning similar to:

This also seems like a good idea to me, however it's a bit more of a lift since you can install multiple plugins at once.

> ⚠️ This plugin is community-maintained. Community-maintained plugins are not actively monitored for security issues and are not verified for integrity. You should always review the contents of a plugin before continuing with the installation.

I think this is unnecessary. If we display the URL I think this is implied.

**Comment by jdxcode** [comment]
What we could do is change the output to something like this to at least communicate it is community maintained:

> This community-maintained plugin will be installed from: hxxps://github.com/username/asdf-1password-cli

**Comment by jsifuentes** [comment]
> What we could do is change the output to something like this to at least communicate it is community maintained:

That could work. I do have a preference for the language I used in my original post because I believe the dangers should be made more directly spelled out rather than risk being inferred from the GitHub URL. If there's hesitancy for wanting to add a recurring warning (like maybe the risk is just inherent in using a tool like rtx), then maybe it could be considered to make it more clear in rtx's README so there's a potential for education before installation. I do see the "Is rtx secure?" section and the SECURITY.md file that does talk about these risks, but it feels a bit buried.

For example, maybe under "About" or "How it works", a warning could read like:

> # About
> ...
> rtx can be configured in many ways. The most typical is by .rtx.toml, but it's also compatible with asdf .tool-versions files. It can also use idiomatic version files like .node-version and .ruby-version. See [Configuration](https://github.com/jdxcode/rtx#configuration) for more.
>
> > :warning: rtx relies on community-maintained plugins and the asdf ecosystem to support over 600 runtimes. You should always exercise caution when installing plugins as it's the equivalent of running untrusted code. The maintainers of rtx are not involved with maintaining community plugins outside of the `rtx-plugins` GitHub user. Read more in [SECURITY.md](SECURITY.md)
