### ISSUE TITLE
Ability to obtain global versions defined in .rtx.toml / config.toml files?

### ISSUE THREAD

**Issue by fgimian** [jdxcode/rtx#803]
Hey there, hope you're doing well. Thanks heaps for this wonderful tool!

I'm attempting to integrate rtx into the Ansible playbooks that setup my development workstation but encountered one little feature that seems to be missing.

Based on the output of `rtx global` show below, he preferred way to configure rtx is using `rtx use` and the global config.toml or local .rtx.toml files.

> A future v2 release of rtx will default to using `~/.config/rtx/config.toml` instead.

However, there doesn't seem to be an equivalent to the `rtx global` command which shows global versions defined in `~/.config/rtx/config.toml`. Using `rtx current` or `rtx ls` may show local versions which have been set in parent directories via `.rtx.toml`, so that may be misleading.

This makes it more tricky to script rtx in tools like Ansible when we want to set the global versions for various tools. Parsing config.toml in such tools is more difficult than a simple command like `rtx global` and would require a TOML parser to be installed etc..

I wonder if there could be an `rtx current -g/--global` option and similarly `rtx ls -g/--global` which would only show versions defined in the global config.toml and .tool_versions global files?

Thanks heaps in advance
Fotis

**Comment by fgimian** [comment]
Thank you so much @jdxcode. Would it be possible to also add this flag to the `rtx current` command too please?

Cheers
Fotis

**Comment by jdxcode** [comment]
that's a hidden command that only exists to retain asdf compatibility. I think the usage of ls and current overlap too much to have separate commands. You should be able to get the information you want with `rtx ls --global | awk '{print $1 "\t" $2}'`

**Comment by fgimian** [comment]
> that's a hidden command that only exists to retain asdf compatibility. I think the usage of ls and current overlap too much to have separate commands.
> 
> You should be able to get the information you want with `rtx ls --global | awk '{print $1 "\t" $2}'`

Sweet, makes sense. Thanks heaps 😄
