### ISSUE TITLE
rtxstatusln should output to stdout instead of stderr?

### ISSUE THREAD

**Issue by eugenesvk** [jdxcode/rtx#82]
Was chasing some weird bug in my added xonsh support module and realized that `rtxstatusln` prints non-quiet messages like `rtx: direnv@2.32.2` to `stderr` instead of `stdout`, and I had a condition that if you `hook-env` command has an error in a captured subprocess, then the stdout shouldn't be passed to the shell for execution.

Is there a reason why status messages are printed as errors?

https://github.com/jdxcode/rtx/blob/f0dc795c84ef20b6ba042fa77cef6adc3a79a129/src/cli/hook_env.rs#L84-L85

https://github.com/jdxcode/rtx/blob/f0dc795c84ef20b6ba042fa77cef6adc3a79a129/src/output.rs#L94-L95

**Comment by jdxcode** [comment]
it's not printed "as an error", it's printed on stderr which is used for status messages like this. You be simply passing output from stderr straight to the user without touching it.

**Comment by jdxcode** [comment]
The reason is that if I put it on stdout, then it would only be parsed by the shell. The user wouldn't see it and the shell would error out.

**Comment by eugenesvk** [comment]
> The reason is that if I put it on stdout, then it would only be parsed by the shell. The user wouldn't see it and the shell would error out.

if you `echo` it or something, the shell will not error out and print the user message to the user
It's just weird to see stderr used for nonerror messages, but ok, will see how to just pass it all through

**Comment by jdxcode** [comment]
that's true, I could put this into the shell script and echo it there. This is still a correct use of stderr though, direnv does exactly the same thing.

**Comment by eugenesvk** [comment]
But that's a mistaken understanding of diagnostics, which is meant to diagnose the cause of an error

This https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout has the **holy POSIX** :) clarification that also matches the most intuitive understanding of what ERRs are for (with added emphasis)

>
>**STDERR**
>...
>**Default Behavior**: When this section is listed as "The standard error shall be used only for diagnostic messages.", it means that, unless otherwise stated, **the diagnostic messages shall be sent to the standard error only when the exit status indicates that an error occurred** and the utility is used as described by this volume of POSIX.1-2008.

This answers sums my view nicely
> Diagnostic messages include error messages, warnings and other messages that are not part of the utility's output when it's operating correctly ("correctly" meaning there is nothing exceptional happening, like files not being found, or whatever it may be).

https://unix.stackexchange.com/questions/336983/when-to-use-standard-error-stream-in-command-line-application


`"rtx: <PLUGIN>@<VERSION>"` message is part of "operating correctly"/"no error occured"
and it's not comparable to curl's justification for why it needs to keep stdout clean and use stderr for logs (since no one bothered to standardize `stdlog` :))
