### ISSUE TITLE
python: take order into account when multiple versions are declared

### ISSUE THREAD

**Issue by pdecat** [jdxcode/rtx#831]
Currently, the following setup selects version 3.9 for the base `python` executable:
```
# rtx use -g system python@3.9 python@3.10
~/.config/rtx/config.toml python@system python@3.9 python@3.10
# which python
/home/patrick/.local/share/rtx/installs/python/3.9.17/bin/python
```

It would be awesome if the order specified on the command line, which is preserved in `~/.config/rtx/config.toml` and `.tool-versions`, was taken into account so that the first one is selected as the default.

**Comment by jdxcode** [comment]
that is how it works, it's just that "system" in rtx is basically a noop. "system" isn't designed to be used this way and so it doesn't add anything to PATH.

I'm not sure if this is even fixable since I don't know where your system python actually is and detecting it is not as simple as you might think.

**Comment by jdxcode** [comment]
what you could do instead is use `path:/some/path` to direct rtx to your actual system python location

**Comment by pdecat** [comment]
Thanks @jdxcode, I did know `path:` was a thing.

However, when I try it, I still get python 3.9 by default:
```
# /usr/bin/python -V
Python 3.11.4
```
```
# rtx use -g python@path:/usr/bin/python python@3.9 python@3.10
~/.config/rtx/config.toml python@path:/usr/bin/python python@3.9 python@3.10

# cat ~/.config/rtx/config.toml
[settings]
missing_runtime_behavior = "warn"
experimental = true

[tools]
python = ["path:/usr/bin/python", "3.9", "3.10"]

# python -V
Python 3.9.17

# rtx reshim

# python -V
Python 3.9.17
```

```
# rtx use -g python@path:/usr/bin/python3.11 python@3.9 python@3.10
~/.config/rtx/config.toml python@path:/usr/bin/python3.11 python@3.9 python@3.10

# cat /home/patrick/.config/rtx/config.toml
[settings]
missing_runtime_behavior = "warn"
experimental = true

[tools]
python = ["path:/usr/bin/python3.11", "3.9", "3.10"]

# python -V
Python 3.9.17

# rtx reshim

# python -V
Python 3.9.17
```

**Comment by jdxcode** [comment]
with `path:` you need to specify the root of a python install, you can't just point to a single binary. For me with homebrew that is: `/opt/homebrew/opt/python@3.9/`

**Comment by pdecat** [comment]
Thanks again, this works great on Ubuntu:

```
# rtx use -g python@path:/usr/ python@3.9 python@3.10
~/.config/rtx/config.toml python@path:/usr/ python@3.9 python@3.10

# python -V
Python 3.11.4

# python3 -V
Python 3.11.4

# python3.9 -V
Python 3.9.17

# python3.10 -V
Python 3.10.9


```

**Comment by jdxcode** [comment]
using `path:/usr/` might have unintended consequences. That is going to add your entire `/usr/bin` to PATH which may have higher priority than you want.

**Comment by jdxcode** [comment]
I realize this isn't great but you could do this:

```
mkdir -p ~/mypython/bin
ln -s /usr/bin/python ~/mypython/bin
```

then set `python path:~/mypython`

**Comment by pdecat** [comment]
How about making rtx discover path to system's `python` before altering `PATH` when `system` is used in its configuration?

**Comment by jdxcode** [comment]
I don't think that's possible. You're only thinking of `python` but there are many bins that python exports and all of them need to be updated:

```
ls ~/.rtx/installs/python/3.11/bin/
2to3@               ansible-galaxy*     idle3.11*           python-config@
2to3-3.11*          ansible-inventory*  pip@                python3@
ansible*            ansible-playbook*   pip3*               python3-config@
ansible-community*  ansible-pull*       pip3.11*            python3.11*
ansible-config*     ansible-test*       pydoc@              python3.11-config*
ansible-connection* ansible-vault*      pydoc3@             python3.11-gdb.py*
ansible-console*    idle@               pydoc3.11*
ansible-doc*        idle3@              python@
```

I have no way to know which of these need to be configured and which do not. They're not the same across python versions.

**Comment by pdecat** [comment]
I must agree these are all good points! I'm starting to better understand how rtx is working :)

**Comment by pdecat** [comment]
> I realize this isn't great but you could do this:
> 
> ```
> mkdir -p ~/mypython/bin
> ln -s /usr/bin/python ~/mypython/bin
> ```
> 
> then set `python path:~/mypython`

That work-around is fine for me, thanks! (note: I had to replace `~` by `/home/path` to make it work)

One last question, what's the point of having a `system` option then?

**Comment by jdxcode** [comment]
Python is the only language that supports using multiple versions at the same time where this is a problem

**Comment by pdecat** [comment]
A bit more context about my use case that may lead to another solution.

I was specifying `system`, in addition to other actual versions, at the global level to get tox run tests for lots of projects that do not use `.tool-versions` files with the last three python minor versions in one run, but still keep my system version the default.

Initially, I had specified `3.11` instead of `system` to achieve this, but then `rtx install` would download and install python 3.11 even though it matched my system version.

Would there be any other option to configure or modify rtx to skip this download and install phase if the default version matches, and create a folder and symbolic links instead, like done in the above mentioned workaround?

**Comment by pdecat** [comment]
Reading other recent issues about python, I guess it is more a pyenv matter than rtx's.

**Comment by jdxcode** [comment]
one option is the following:

```
mkdir -p ~/.local/share/rtx/installs/python/default/bin
ln -s /usr/bin/python ~/.local/share/rtx/installs/python/default/bin
```

You can use a different name from "default", however you can't use "system" as that's treated differently. With this you can specify "default" as the version instead of "path:...`. That's not really going to do anything differently, but at least you don't need to specify the full path in your global config.

**Comment by jdxcode** [comment]
Notably for homebrew this isn't really a problem since there is a directory for each python version, e.g.: `/opt/homebrew/Cellar/python@3.9` that you can specify. However your system package manager may or may not provide a directory like that.
