### ISSUE TITLE
Python shims with version suffixes report no version selected

### ISSUE THREAD

**Issue by mgilbey** [jdxcode/rtx#838]
**Describe the bug**
When using a python shim with a version suffix such as `python3.10 --version`, rather than select a version of python 3.10.x the user is instead presented with a error message stating no version is set.

```
~ % rtx ls python
python 2.7.18
python 3.10.12
~ % python3.10 --version
rtx No version is set for shim: python3.10
Set a global default version with one of the following:
rtx use -g python@3.10.12
```

**To Reproduce**

Install a version of python, and use the shim for it where the shim version does not match the system or global version. Reshim and add shims to PATH.

```
rtx install python@3.10;
rtx reshim;
export PATH="$HOME/.local/share/rtx/shims:$PATH";
which python3.10;
```

**Expected behavior**
The shim should select the installed and matching python version, or perhaps the shim should not be installed to utilize the default `python3` or `python` shim / install.

**`rtx doctor` output**

```
~ % rtx doctor
rtx version:
  2023.8.6 macos-arm64 (2023-08-23)

build:
  Target: aarch64-apple-darwin
  Features: BREW, DEFAULT, NATIVE_TLS
  Built: Wed, 23 Aug 2023 01:35:26 +0000
  Rust Version: rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball)
  Profile: release

shell:
  /opt/homebrew/bin/zsh
  zsh 5.9 (arm-apple-darwin21.3.0)

rtx data directory:
  /Users/mgilbey/.local/share/rtx

rtx environment variables:
  RTX_SHELL=zsh

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:

plugins:
  firebase    https://github.com/jthegedus/asdf-firebase.git#7eb5359
  go          (core)
  java        https://github.com/rtx-plugins/rtx-java.git#94b7f02
  node        (core)
  pnpm        https://github.com/jonathanmorley/asdf-pnpm.git#ea033db
  python      (core)
  ruby        (core)
  sourcery    https://github.com/younke/asdf-sourcery.git#1ddd8f1
  swift       https://github.com/fcrespo82/asdf-swift.git#23dbd46
  swiftlint   https://github.com/klundberg/asdf-swiftlint.git#79f2c6e

toolset:


No problems found
```

**Additional context**
I had no global version of python set (i.e. use the system version) which is currently the homebrew version of python **3.11** at `/opt/homebrew/opt/python/libexec/bin/python`, which works via the regular `python` or `python3` shim.

```
~ % ls .local/share/rtx/shims/python*
.local/share/rtx/shims/python			.local/share/rtx/shims/python2.7		.local/share/rtx/shims/python3-config
.local/share/rtx/shims/python-config		.local/share/rtx/shims/python2.7-config		.local/share/rtx/shims/python3.10
.local/share/rtx/shims/python2			.local/share/rtx/shims/python2.7-gdb.py		.local/share/rtx/shims/python3.10-config
.local/share/rtx/shims/python2-config		.local/share/rtx/shims/python3			.local/share/rtx/shims/python3.10-gdb.py
```

**Comment by jdxcode** [comment]
It would be a mistake for me to do what you're asking here. rtx does not use runtimes that are not selected by some config and doing so would make rtx start behaving in an inconsistent way.

If you want this behavior, you need to explicitly all of the python versions as globals: `rtx use -g python@3.11 python@3.10 python@3.9 ...`

**Comment by mgilbey** [comment]
Is the very nature a of a shim with a version on the path not the equivalent to having some config select a version? It seems counter intuitive for the shims to exist if they cannot function without a corresponding config version, and clunky to keep the global list maintained whenever a version in installed / removed.

The fact that rtx creates the shim seems counter to rtx not intervening unless configuration dictates so.

Is there any option to not produce these versioned shims if this is working as expected?

I think this is a fantastic project and found this an odd quirk for what is otherwise a very slick / low maintenance solution!

**Comment by jdxcode** [comment]
I think you're seeing the "3.9" at the end of a filename and incorrectly assuming that rtx should be able to map those to a python version but that is not how it works. rtx is completely ignorant of which bins an installation has. All rtx does is take the `/bin` of a given python installation and add all of those to PATH. In the case of shims it does the same. If nothing matching that shim is selected, it cannot match it to an installed version. rtx has no capability of understanding that "python3.9" should map to python@3.9. As far as rtx is concerned "python3.9" is just the name of a bin that's no different than "python" or "pip".

Attempting this has a lot of consequences you are not aware of. For a start, I would be adding an _unselected_ runtime to PATH which is something rtx never does. This would be surprising and strange behavior.

Also, what if the user has python@3.9.0 and python@3.9.1 installed? Both of those output python3.9 bins. Also, _any_ plugin can output a python binary, not just the python core plugin. This means you can write your own python plugin and name it whatever you want, how should those bins be treated?

**Comment by mgilbey** [comment]
Thank you for the explanation @jdxcode - that's clear why this is not something that rtx should be attempting to implement and why the error messaging / solution is thus.

**Comment by jdxcode** [comment]
if you want to take a stab at clarifying this behavior in [python.md](https://github.com/jdxcode/rtx/blob/main/docs/python.md) I think it might help. I looked and it does explain how to set multiple runtimes, but maybe it should explain some of the why.
