### ISSUE TITLE
move commands out of README and into their own files

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#84]
we should have a structure like this for the command help:

* README.md
* docs/
  * commands.md # command index
  * commands/
    * activate.md
    * exec.md
    * ...
    * plugins/
      * install.md
      * list.md
      * ...

This is a relatively easy change, the code is all in `src/cli/render_help.rs`. The hardest part is going to be that currently that command outputs text. I think that has to change and it will need to write the files directly. This means the pre-commit hook in ./justfile will also need to be updated slightly.

**Comment by blopker** [comment]
For what it's worth, I actually prefer one large README instead of multiple files. Makes it easy to search using the browsers built in tools.

**Comment by jdxcode** [comment]
That's a fair point, maybe we should just leave it

**Comment by blopker** [comment]
Maybe instead, generate a ToC with something like https://github.com/jonschlinkert/markdown-toc ? Seems like the best of both worlds. (or https://crates.io/crates/markdown-toc, but seems outdated)

**Comment by blopker** [comment]
Actually, I just saw this: https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/ 
It's not as good as inline, but it's already there!
