### ISSUE TITLE
inconsistency with `rtx where`

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#92]
`rtx where` is a bit overloaded. I think a lot of people want to use it so that they can pick whichever is the current* version  of a runtime. However, in the case where there _isn't_ an active version (like if you run `rtx where python`, but no parent `.tool-versions` file actually has python mentioned, then `rtx where` will show the _latest_ version. (EDIT: as @amoosbr notes, this actually isn't even working properly)

I think in some cases people would prefer this is an error instead.

The reason `rtx where python` shows the latest installed is because that's essentially an alias for running `rtx where python@latest`, which you would expect to show you the latest _installed_ version.

I'm not entirely sure what we want to do here but I think we could make this behave more predictably.

One idea is we could add a `--current` flag to limit `rtx where` to only show active versions. Or we could make it so if you don't specify a version prefix with `@...`, then it only shows current and installed otherwise. I _think_ the latter might be a little more along what users would expect to happen.

(* "current" in rtx-speak means "in a .tool-versions file or otherwise specified, like via `--runtime` or environment variable")

**Comment by amoosbr** [comment]
I actually didn't think yet of the expected behavior, when no global version is set. I probably would have expected an error.

Just testing this with `rtx where python` with no `python` version set in my global .tool-versions file was actually pretty non-deterministic. That's for sure not expected. :-)

```sh
❯ cat ~/.tool-versions
nodejs 18
java temurin-17
golang 1.19
ruby 3.1
❯ rtx ls -p python
   python 2.7.18
   python 3.8.10
   python 3.9.12
   python 3.10.9
   python 3.11.1
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/3.9.12
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/2.7.18
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/3.8.10
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/3.10.9
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/3.10.9
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/2.7.18
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/3.9.12
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/2.7.18
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/2.7.18
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/2.7.18
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/2.7.18
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/2.7.18
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/2.7.18
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/3.8.10
❯ rtx where python
/Users/user/.local/share/rtx/installs/python/3.9.12
```

Thinking of what to expect, I guess another influence is if a plugin is installed for the tool or not. I.e. with asdf, I had additional global tools with version set to `system`. When a plugin is installed, having no version set would for me default to `system`.

I'm not 100% sure, I understood, what you had in mind with `...then it only shows current and installed otherwise...`, but I also would not have expected `latest`.

**Comment by jdxcode** [comment]
I think if you put the "@" in that should be an indication to ignore the current active version and just fetch whatever installed version matches. After thinking about this I think this is the behavior we want:

```
rtx install python # should install either the current version or latest if no version set
rtx env -r python # should use either the current version or latest if no version set
rtx exec python # should use either the current version or latest if no version set
rtx where python # should _only_ use current version

# the following should all use the latest available version and ignore what is installed/not installed
rtx install python@latest
rtx env -r python@latest
rtx exec python@latest
rtx where python@latest # this should error if the most recent version isn't installed
```

**Comment by jdxcode** [comment]
So when I first wrote rtx I was thinking of the following use-case:

```
$ rtx install nodejs@20.0.0
$ rtx latest nodejs@20
20.0.1 # this version is not installed but it is the latest available to install
$ rtx exec nodejs@20 -- node -v
20.0.0
```

My thinking is that I wanted to avoid users from hitting an error just because a new version of node came out. I wanted rtx to use the latest matching version that was installed. If you put `nodejs 20` in your `.tool-versions`, you'll see a warning if a new version comes out.

Now I'm thinking this isn't the right behavior. It's complex because it needs to behave differently in different commands. I think users probably will expect `nodejs@20` to point to the same version throughout rtx, not sometimes use the latest installed and sometimes the latest available. It should always point to the latest available.
