### ISSUE TITLE
Unable to install older Java (x86_64) versions

### ISSUE THREAD

**Issue by roele** [jdxcode/rtx#95]
While `asdf` allowed to install older Java versions (compiled for x86_64) via `arch`, this seems not possible with `rtx`.

```
❯ arch -x86_64 rtx install java@openjdk-11.0.2
arch: posix_spawnp: rtx: Bad CPU type in executable
```

As a workaround i manually downloaded the version and placed it in `~/.local/share/rtx/installs/java` which seemed to work so far. Anything else to consider?

**Comment by jdxcode** [comment]
maybe this is because you're using the arm64 version of rtx. You could try the x64 version to see what happens.

**Comment by roele** [comment]
I generally understand the limitation as i'm on a M1 Mac Book using a ARM64 binary. Unlike asdf which is purely shell based and hence does not have this limitation.

Anyways i figured that i also need to write a `.rtxconf.msgpack` file to make my workaround work.

**Comment by jdxcode** [comment]
Huh, I suppose I could put the architecture into that file name so that it wouldn’t be automatically loaded in different architecutures

**Comment by roele** [comment]
Your suggestion would render my workaround useless, as i understand this. Since i'm on M1 i still need to be able run old stuff (like Java 11), so i'm fine with the state as as. I'm just curious what this file is used for exactly. It seem like its currently defining the PATH for that runtime.

**Comment by roele** [comment]
An issue i just discovered though. Using a `.tool-versions` file in a project shows the openjdk-11.0.2 as selected but also reports an error.

```
 ❯ rtx list
-> java openjdk-11.0.2     (set by ~/Dev/playground/java/example/.tool-versions)
   java openjdk-17.0.2
   java openjdk-19.0.2
-> maven 3.8.7              (set by ~/.tool-versions)
[ERROR] failed to fetch runtimeconf for java@openjdk-11.0.2
[ERROR] Run with RTX_DEBUG=1 for more information.
```

Checking the version shows that the autoselection did not work successfully.
```
 ❯ java --version
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
[ERROR] failed to fetch runtimeconf for java@openjdk-11.0.2
[ERROR] Run with RTX_DEBUG=1 for more information.
```

**Comment by roele** [comment]
After some more testing, i can confirm that things work with my workaround. Looks like i can switch to `rtx` not looking back. 

Issue can be closed from my point of view. Thanks for clarifying my questions.

**Comment by jdxcode** [comment]
glad to hear it! lmk if there is anything more we might be able to do here. I couldn't think of anything off the top of my head.
